---
title: "Nature of science"
subtitle: "Fundamental bases of science teaching for scientific literacy"
filename: fac-ndc
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: How does science know what it knows? How do you build knowledge? What are the limitations?
categories: [nature, learning, teaching, science]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

# Nature of science

## Presentation

> Professor Diego Sanjulián Alonso directs this part of the Fundamentals of Learning and Teaching of Natural Sciences module called **nature of science**, where the nature of science is addressed with different questions: How does science know what it knows? How do you build knowledge? What are the limitations? Three theoretical sessions have been held, another three asynchronous sessions and a group session that involved a presentation of the group work.

## Didactic material for all sessions

::: callout-tip
## Click on each of the tabs to view the material of each session
:::

::: {.panel-tabset}
## Session 1 {.active}

<embed src="/files/NdC-docs/NdC-sesion1.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 2

<embed src="/files/NdC-docs/NdC-sesion2.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 3

<embed src="/files/NdC-docs/NdC-sesion3.pdf" type="application/pdf" width="100%" height="800px"/>

:::


::: {.column-margin}
**Supporting documentation**

- [Analysis of cognitive biases](/files/NdC-docs/Analisisdebiasescognitivos.pdf){.highlight width="10%" target="_blank"}

- [Analysis of fallacies](/files/NdC-docs/AnalisisdeFalacias.pdf){.highlight width="10%" target="_blank"}

- [Assaig 12](/files/NdC-docs/Assaig12.pdf){.highlight width="10%" target="_blank"}

- [Balance of arguments](/files/NdC-docs/Balanzadeargumentos.pdf){.highlight width="10%" target="_blank"}

- [CESINF](/files/NdC-docs/CESINF.pdf){.highlight width="10%" target="_blank"}

- [Classification of information and arguments](/files/NdC-docs/Classificaciondeinformacionyargume.pdf){.highlight width="10%" target="_blank"}

- [Exemples per construct](/files/NdC-docs/ExemplesperConstruir.pdf){.highlight width="10%" target="_blank"}

- [Congress review guide](/files/NdC-docs/GuiaReviewCongres.pdf){.highlight width="10%" target="_blank"}

- [Critical reading in 3 steps](/files/NdC-docs/Lecturacriticaen3pasos.pdf){.highlight width="10%" target="_blank"}

- [Llista d'articles](/files/NdC-docs/LlistaArticles.pdf){.highlight width="10%" target="_blank"}

- [Template CSC assaig](/files/NdC-docs/PlantillaCSCAssaig.pdf){.highlight width="10%" target="_blank"}

- [Critical text reading template](/files/NdC-docs/PlantillaLecturacriticadetextos.pdf){.highlight width="10%" target="_blank"}

- [Rubrica McLeares](/files/NdC-docs/RubricaMcLeares.pdf){.highlight width="10%" target="_blank"}

- [Poster rubric](/files/NdC-docs/RubricaPoster.pdf){.highlight width="10%" target="_blank"}

- [Rubrica oral presentations](/files/NdC-docs/RubricaPresentacionsOrals.pdf){.highlight width="10%" target="_blank"}

- [Source validation table](/files/NdC-docs/Tablevalidaciondefuentes.pdf){.highlight width="10%" target="_blank"}

- [Targetes converses socràtiques](/files/NdC-docs/TargetesConvSocratics.pdf){.highlight width="10%" target="_blank"}

- [Cacera d'arguments](/files/NdC-docs/caceraarguments.pdf){.highlight width="10%" target="_blank"}

- [Criteris per an articles](/files/NdC-docs/criterisarticles.pdf){.highlight width="10%" target="_blank"}

- [Research guide](/files/NdC-docs/guiorecerca.pdf){.highlight width="10%" target="_blank"}

- [Model article 2](/files/NdC-docs/modelarticle2.pdf){.highlight width="10%" target="_blank"}

- [Superstructure poster](/files/NdC-docs/superestructuraPoster.pdf){.highlight width="10%" target="_blank"}

- [Mythical scientific text](/files/NdC-docs/textCientificMitic.pdf){.highlight width="10%" target="_blank"}
:::

## Material for asynchronous and group work

::: callout-tip
## Click on each of the tabs to view the material for each job
:::

::: {.panel-tabset}
## Asynchronous 1 - Creativity {.active}

<embed src="/files/NdC-docs/NdC-SA1.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 1 - Creativity Presentation

<embed src="/files/NdC-docs/NdC-SA1-Creativitat.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 1 - Cinema Presentation

<embed src="/files/NdC-docs/NdC-SA1-Cinema.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 2a - Critical thinking

<embed src="/files/NdC-docs/NdC-SA2a.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 2b - Critical thinking

<embed src="/files/NdC-docs/NdC-SA2b.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 2 - Presentation Critical reading

<embed src="/files/NdC-docs/NdC-SA2-Lectura-critica.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 3 - Scientific expression

<embed src="/files/NdC-docs/NdC-SA3.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous 3 - Presentation Scientific expression

<embed src="/files/NdC-docs/NdC-SA3-Expression-cientifica.pdf" type="application/pdf" width="100%" height="800px"/>

## Group 1 Report

<embed src="/files/NdC-docs/NdC-tasca-grupal-doc.pdf" type="application/pdf" width="100%" height="800px"/>

## Group 2 Presentation

<embed src="/files/NdC-docs/NdC-tasca-grupal-presentation.pdf" type="application/pdf" width="100%" height="800px"/>
:::