---
title: "Naturaleza de la ciencia"
subtitle: "Bases fundamentales de la didáctica de las ciencias para la alfabetización científica"
filename: fac-ndc
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: ¿Cómo sabe la ciencia lo que sabe? ¿Cómo construye el conocimiento? ¿Cuáles son las limitaciones?
categories: [naturaleza, aprendizaje, enseñanza, ciencia]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

# Naturaleza de la ciencia

## Presentación

> El profesor Diego Sanjulián Alonso dirige esta parte del módulo de Fundamentos del Aprendizaje y Enseñanza de las Ciencias Naturales denominado **naturaleza de la ciencia**, donde se aborda la naturaleza de la ciencia con diferentes preguntas: ¿Cómo sabe la ciencia lo que sabe? ¿Cómo construye el conocimiento? ¿Cuáles son las limitaciones?. Se han realizado tres sesiones teóricas, otras tres sesiones asincrónicas y una sesión grupal que conllevaba una presentación del trabajo grupal.

## Material didáctico de todas las sesiones

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de cada sesión
:::

::: panel-tabset
## Sesión 1 {.active}

<embed src="/files/NdC-docs/NdC-sesion1.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/NdC-docs/NdC-sesion2.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 3

<embed src="/files/NdC-docs/NdC-sesion3.pdf" type="application/pdf" width="100%" height="800px"/>

:::


::: column-margin
**Documentación de apoyo**

- [Análisis de biases cognitivos](/files/NdC-docs/Analisisdebiasescognitivos.pdf){.highlight width="10%" target="_blank"}

- [Análisis de falacias](/files/NdC-docs/AnalisisdeFalacias.pdf){.highlight width="10%" target="_blank"}

- [Assaig 12](/files/NdC-docs/Assaig12.pdf){.highlight width="10%" target="_blank"}

- [Balanza de argumentos](/files/NdC-docs/Balanzadeargumentos.pdf){.highlight width="10%" target="_blank"}

- [CESINF](/files/NdC-docs/CESINF.pdf){.highlight width="10%" target="_blank"}

- [Clasificación de información y argumentos](/files/NdC-docs/Classificaciondeinformacionyargume.pdf){.highlight width="10%" target="_blank"}

- [Exemples per construir](/files/NdC-docs/ExemplesperConstruir.pdf){.highlight width="10%" target="_blank"}

- [Guía review congrés](/files/NdC-docs/GuiaReviewCongres.pdf){.highlight width="10%" target="_blank"}

- [Lectura crítica en 3 pasos](/files/NdC-docs/Lecturacriticaen3pasos.pdf){.highlight width="10%" target="_blank"}

- [Llista d'articles](/files/NdC-docs/LlistaArticles.pdf){.highlight width="10%" target="_blank"}

- [Plantilla CSC assaig](/files/NdC-docs/PlantillaCSCAssaig.pdf){.highlight width="10%" target="_blank"}

- [Plantilla lectura crítica de textos](/files/NdC-docs/PlantillaLecturacriticadetextos.pdf){.highlight width="10%" target="_blank"}

- [Rúbrica McLeares](/files/NdC-docs/RubricaMcLeares.pdf){.highlight width="10%" target="_blank"}

- [Rúbrica póster](/files/NdC-docs/RubricaPoster.pdf){.highlight width="10%" target="_blank"}

- [Rúbrica presentacions orals](/files/NdC-docs/RubricaPresentacionsOrals.pdf){.highlight width="10%" target="_blank"}

- [Tabla de validación de fuentes](/files/NdC-docs/Tabladevalidaciondefuentes.pdf){.highlight width="10%" target="_blank"}

- [Targetes converses socràtiques](/files/NdC-docs/TargetesConvSocratics.pdf){.highlight width="10%" target="_blank"}

- [Cacera d'arguments](/files/NdC-docs/caceraarguments.pdf){.highlight width="10%" target="_blank"}

- [Criteris per a articles](/files/NdC-docs/criterisarticles.pdf){.highlight width="10%" target="_blank"}

- [Guió de recerca](/files/NdC-docs/guiorecerca.pdf){.highlight width="10%" target="_blank"}

- [Model article 2](/files/NdC-docs/modelarticle2.pdf){.highlight width="10%" target="_blank"}

- [Superestructura póster](/files/NdC-docs/superestructuraPoster.pdf){.highlight width="10%" target="_blank"}

- [Text científic mític](/files/NdC-docs/textCientificMitic.pdf){.highlight width="10%" target="_blank"}
:::

## Material de los trabajos asincrónicos y grupal

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de cada trabajo
:::

::: panel-tabset
## Asíncrona 1 - Creatividad {.active}

<embed src="/files/NdC-docs/NdC-SA1.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 1 - Presentación Creatividad

<embed src="/files/NdC-docs/NdC-SA1-Creativitat.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 1 - Presentación Cine

<embed src="/files/NdC-docs/NdC-SA1-Cinema.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 2a - Pensamiento crítico

<embed src="/files/NdC-docs/NdC-SA2a.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 2b - Pensamiento crítico

<embed src="/files/NdC-docs/NdC-SA2b.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 2 - Presentación Lectura crítica

<embed src="/files/NdC-docs/NdC-SA2-Lectura-critica.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 3 - Expresión científica

<embed src="/files/NdC-docs/NdC-SA3.pdf" type="application/pdf" width="100%" height="800px"/>

## Asíncrona 3 - Presentación Expresión científica

<embed src="/files/NdC-docs/NdC-SA3-Expression-cientifica.pdf" type="application/pdf" width="100%" height="800px"/>

## Grupal 1 Informe

<embed src="/files/NdC-docs/NdC-tasca-grupal-doc.pdf" type="application/pdf" width="100%" height="800px"/>

## Grupal 2 Presentación

<embed src="/files/NdC-docs/NdC-tasca-grupal-presentation.pdf" type="application/pdf" width="100%" height="800px"/>
:::