---
title: "Trabajos prácticos"
subtitle: "Bases fundamentales de la didáctica de las ciencias para la alfabetización científica"
filename: fac-trabajos-practicos
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description:  Analizar por qué se hace trabajo experimental en las clases de ciencias (finalidad del trabajo experimental), asi como reflexionar sobre cómo se puede desarrollar mejor la comprensión y procedimientos de los estudiantes a través del trabajo experimental.
categories: [práctica, laboratorio, experimento, aprendizaje, enseñanza]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

# Trabajos prácticos

## Introducción

> El profesor Xavier Muñoz dirige esta parte del módulo de Fundamentos del Aprendizaje y Enseñanza de las Ciencias Naturales denominado **trabajos prácticos**, con los objetivos de analizar por qué se hace trabajo experimental en las clases de ciencias (finalidad del trabajo experimental), asi como reflexionar sobre cómo se puede desarrollar mejor la comprensión y procedimientos de los estudiantes a través del trabajo experimental. Fnalmente, explorar como presentar las actividades experimentales de forma que realmente ayuden a la construcción de conocimiento científico

## Material didáctico de todas las sesiones

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de cada sesión y material didáctico
:::

::: {.panel-tabset}
## Sesión 1 {.active}

<embed src="/files/fac-trabajos-practicos/fac-treballs-practics-S1.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/fac-trabajos-practicos/fac-treballs-practics-S2.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 3

<embed src="/files/fac-trabajos-practicos/fac-treballs-practics-S3.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Material didáctico de apoyo

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material didáctico de apoyo
:::

::: {.panel-tabset}


## 24 Experimentos para el aula con material sencillo {.active}

<embed src="/files/fac-trabajos-practicos/fac-activitats-practiques.pdf" type="application/pdf" width="100%" height="800px"/>

## Experimento de Coca-Cola con Mentos

<embed src="/files/fac-trabajos-practicos/fac-Mentos-cocacola.pdf" type="application/pdf" width="100%" height="800px"/>

## Experimento del volcan de burbujas

<embed src="/files/fac-trabajos-practicos/fac-volcan-burbujas-limon.pdf" type="application/pdf" width="100%" height="800px"/>

## Disección de corazón - Guía del profesorado

<embed src="/files/fac-trabajos-practicos/fac-Disseccio_cor_Guia_professorat.pdf" type="application/pdf" width="100%" height="800px"/>

## Fotosíntesis - Guía

<embed src="/files/fac-trabajos-practicos/fac-Fotosintesi-guia.pdf" type="application/pdf" width="100%" height="800px"/>

## Modelo de célula

<embed src="/files/fac-trabajos-practicos/fac-Model-cellula.pdf" type="application/pdf" width="100%" height="800px"/>

## Ósmosis

<embed src="/files/fac-trabajos-practicos/fac-Osmosi-Motic.pdf" type="application/pdf" width="100%" height="800px"/>

## Respiración de plantas

<embed src="/files/fac-trabajos-practicos/fac-Respiracion-plantes.pdf" type="application/pdf" width="100%" height="800px"/>

## Tinción de Gram

<embed src="/files/fac-trabajos-practicos/fac-gram.pdf" type="application/pdf" width="100%" height="800px"/>

## Mitosis

<embed src="/files/fac-trabajos-practicos/fac-mitosi.pdf" type="application/pdf" width="100%" height="800px"/>

## UPF - Galería de prácticas

<embed src="/files/fac-trabajos-practicos/fac-UPF-Galeria-practiques.pdf" type="application/pdf" width="100%" height="800px"/>

:::