---
title: "CV analysis"
subtitle: "CV's of Natural Sciences specialties (Biology and Geology / Physics and Chemistry)"
filename: cfd-analisis-cv
author: "Pedro Martinez Duran"
date-modified: last-modified
date-format: full
description: Analysis of the CV's of the Natural Sciences specialties (Biology and Geology / Physics and Chemistry)
categories: [analysis, CV, resume]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentation

> Professor Xavier Muñoz Báguena directs this part of the **Disciplinary Training Complements** module called **analysis of secondary education curricula**, with the objectives of knowing the natural sciences curriculum of ESO and high school, reflecting on the teaching-learning objectives of natural sciences in secondary school (purposes of the curriculum) and finally analyzing external tests (4th ESO).

## Session material

::: callout-tip
## Click on each of the tabs to view the material of each session
:::

::: panel-tabset
## Session 1 {.active}

<embed src="/files/CFD-analisis-CV.pdf" type="application/pdf" width="100%" height="800px"/>

## Decree 175/2022

<embed src="/files/Decret-CVE-DOGC.pdf" type="application/pdf" width="100%" height="800px"/>

## LOE+LOMLOE

<embed src="/files/loe-completa-con-lomloe.pdf" type="application/pdf" width="100%" height="800px"/>

## Evaluate to learn

<embed src="/files/avaluar_per_aprendre.pdf" type="application/pdf" width="100%" height="800px"/>

## Priority areas

<embed src="/files/CFD_ambitos-prioritarios.pdf" type="application/pdf" width="100%" height="800px"/>

## classroom competency CV

<embed src="/files/CFD-CV-competencial-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## CE Recommendation

<embed src="/files/CFD_recomanacion-CE.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2024/25

::: panel-tabset
## Science Quiz 2024/25 {.active}

<embed src="/files/cfd-prova-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

## Answer sheet 2024/25

<embed src="/files/cfd-full-respostes-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2024/25

<embed src="/files/cfd-criteris-correccio-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2022/23

::: panel-tabset
## Science Test 2022/23 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_22_23.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2022/23

<embed src="/files/provas-competencias-ct/Solucions/CBCT_22_23_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2022/23

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_22_23Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological skills 2020/21

::: panel-tabset
## Science Quiz 2020/21 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_20_21.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2020/21

<embed src="/files/provas-competencias-ct/Solucions/CBCT_20_21_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2020/21

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_20_21Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2019/20

::: panel-tabset
## Science Quiz 2019/20 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_19_20.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2019/20

<embed src="/files/provas-competencias-ct/Solucions/CBCT_19_20_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2019/20

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_19_20Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2018/19

::: panel-tabset
## Science Test 2018/19 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_18_19.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2018/19

<embed src="/files/provas-competencias-ct/Solucions/CBCT_18_19_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2018/19

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_18_19Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2017/18

::: panel-tabset
## Science Test 2017/18 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_17_18.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2017/18

<embed src="/files/provas-competencias-ct/Solucions/CBCT_17_18_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2017/18

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_17_18Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2016/17

::: panel-tabset
## Science Test 2016/17 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_16_17.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2016/17

<embed src="/files/provas-competencias-ct/Solucions/CBCT_16_17_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2016/17

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_16_17Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentation of the final evaluation of 4 ESO of scientific-technological competencies 2015/16

::: panel-tabset
## Science Test 2015/16 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_15_16.pdf" type="application/pdf" width="100%" height="800px"/>

## Solutions 2015/16

<embed src="/files/provas-competencias-ct/Solucions/CBCT_15_16_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Correction criteria 2015/16

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_15_16Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

