---
title: "Geology"
subtitle: "Integrated guide to the Natural Sciences specialty in Geology"
filename: cfd-geologia
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Subject that covers the specific aspects of the Geology curriculum in secondary education
categories: [accessories, discipline, geology]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentation

> Professor Laia Ramon-Sala directs this part of the **Disciplinary Training Complements** module called **Geology and Environmental Sciences**, with the objectives of knowing the curriculum of geology and environmental sciences of ESO and high school, and reflecting on the objectives of teaching-learning of natural sciences in secondary school.

## Didactic material for the sessions and the work to be done

::: callout-tip
## Click on each of the tabs to view the material from the initial session and the documentation associated with the work to be done
:::

::: {.panel-tabset}
## Initial session {.active}

<embed src="/files/cfd-docs/cfd-geologia-intro.pdf" type="application/pdf" width="100%" height="800px"/>

## Additional bibliography

<embed src="/files/cfd-docs/cfd-geo-bibliografia.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Links of interest for the subject

- [Guide to rocks from the Museu de Ciències de Catalunya](https://museuciencies.cat/comunicacio/publicacions/divulgatives/guia-de-roques/)

- [Dictionary of geology](https://cit.iec.cat/DGEOL/default.asp?opcio=0)

### RAPAKIVI - @jpereztar

{{< video https://www.youtube.com/watch?v=T2dbGA4vsEE aspect-ratio="4x3" >}}

### Fossil Rock Anthem

{{< video https://youtu.be/ClJ5lwl_wM0 aspect-ratio="4x3" >}}


::: {.column-margin}
**Supporting documentation**

- [Geology test year 19/20](/files/cfd-docs/cfd-geo-geologia-provaA-competencia-geologica.pdf){.highlight width="10%" target="_blank"}

- [Correction Geology test year 19/20](/files/cfd-docs/cfd-geo-geologia-provaA-correccion.pdf){.highlight width="10%" target="_blank"}

- [Geology test year 20/21](/files/cfd-docs/cfd-geo-prova-20-21.pdf){.highlight width="10%" target="_blank"}

- [Correccion Geology test year 20/21](/files/cfd-docs/cfd-geo-correccion-prova-20-21.pdf){.highlight width="10%" target="_blank"}

- [Geology test year 21/22](/files/cfd-docs/cfd-geo-prova-21-22.pdf){.highlight width="10%" target="_blank"}

- [Correction Geology test year 21/22](/files/cfd-docs/cfd-geo-correccion-prova-21-22.pdf){.highlight width="10%" target="_blank"}

:::

## Task 1 "Gaia, the Great Mother"

In this task the following learning objectives will be worked on:

- Argue the knowledge of the different elements of the Earth system, as well as the interactions between them at the local level and at the global level, to predict the dynamics of a system.

- Identify situations and explain examples of paradigmatic changes that have led to major scientific controversies in the history of science.

To achieve the objectives, watch the two videos and perform the indicated tasks, individually. The first has a narrative character appropriate for an ESO level, doing the same task. The second has a purely didactic nature and is quite dense. It will serve to introduce or review key concepts in geology, but doing this activity in the classroom would be too heavy.

### Video 1: Gaia, the great mother

48' documentary about the origin, evolution and future of the Earth, with emphasis on geological concepts and the role of life and humans. Facts and ideas are shown through illustrations and animations, as well as films taken in places such as museums and nearby relevant landscapes. Threats to the sustainability of the planet are also exposed. There are three types of questions:

- Questions that you have to answer before starting to watch the documentary.

- Questions that you have to answer while watching the documentary.

- Questions you have to answer after watching the documentary.

For this reason you have about two hours to complete the questionnaire, although I have not set a limit.

After watching the documentary and answering the questionnaire, make a contribution to one of the forum debates, taking into account what your colleagues have responded to.

{{< video https://youtu.be/OL6U_1WmBbw aspect-ratio="4x3" >}}

### Video 2: The depths of the Earth

53' informative program on the internal dynamics of the planet, focusing on volcanic and seismic phenomena, but also exposing the different composition of the Earth's layers and their movement. Facts and ideas are shown through animations and analog teaching models, as well as films made in places such as museums and relevant nearby landscapes. There are three types of questions:

- Questions that you have to answer before starting to watch the informative program.

- Questions that you have to answer while viewing the informative program.

- Questions that you have to answer after watching the informative program.

[See informative program: The depths of the Earth](https://www.rtve.es/play/videos/curioseando/curioseando-t2-programa-5-profundidades-tierra/16444938/){target="_blank"}

## Task 2 "Everyday minerals"

::: {.panel-tabset}
## Initial presentation {.active}

<embed src="/files/cfd-docs/cfd-geo-minerals-quotidians.pdf" type="application/pdf" width="100%" height="800px"/>

## Practical activity of everyday minerals

<embed src="/files/cfd-docs/cfd-tasca-minerals-quotidians.pdf" type="application/pdf" width="100%" height="800px"/>

:::

### How the earth works - part 1

[See video: How the earth works - part 1](file:///C:/Users/pedro/Documents/shared_VMs/Tasca2/view1.htm){target="_blank"}

### How the earth works - part 2

[See video: How the earth works - part 2](https://aulaglobal.upf.edu/mod/kalvidres/view.php?id=1665785){target="_blank"}


## Task 3 "The fill and its lithology"

::: {.panel-tabset}
## Initial presentation {.active}

<embed src="/files/cfd-docs/cfd-geo-presentacion-relleu.pdf" type="application/pdf" width="100%" height="800px"/>

## What is geological history?

<embed src="/files/cfd-docs/cfd-geo-historia-geologica.pdf" type="application/pdf" width="100%" height="800px"/>

## Description of task 3

<embed src="/files/cfd-docs/cfd-geo-tasca3-relleu.pdf" type="application/pdf" width="100%" height="800px"/>

:::

### The geological fill

[See video: The geological fill](https://aulaglobal.upf.edu/mod/kalvidres/view.php?id=1629089){target="_blank"}


## Task 4 "Interdependence - Recent news"

::: {.panel-tabset}
## Initial presentation {.active}

<embed src="/files/cfd-docs/cfd-geo-relacion-tierra.pdf" type="application/pdf" width="100%" height="800px"/>

## Interdependence - Recent news

<embed src="/files/cfd-docs/cfd-geo-noticia-reciente.pdf" type="application/pdf" width="100%" height="800px"/>

:::





