---
title: "Marc educatiu"
subtitle: "Context i normativa del sistema educatiu català"
filename: sofe-marco-educativo
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Context i normativa del sistema educatiu català per al professorat que s'incorpora al sistema educatiu català, amb èmfasi en el marc legal i les oportunitats laborals.
categories: [educació, sistema educatiu, normatives, ensenyament, ocupació, formació, educació superior, política educativa]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> El professor Lluís Pagès dirigeix ​​aquesta part del mòdul **societat, família i educació: processos i contextos educatius** denominat **marc educatiu**, que aborda com incorporar-se al sistema educatiu català com a docent, entenent el context particular que l'envolta i sabent com relacionar-se amb els diferents equips i agents socials, per complir amb èxit la funció educativa. Això implica conèixer les principals característiques del sistema educatiu català i del centre particular en el qual ens incorporem i saber desenvolupar una tasca eficaç que contribueixi a formar l'alumnat de manera satisfactòria. A més, conèixer la documentació i la normativa i saber aprofitar els diferents casos reals treballats en el màster per resoldre els reptes que es plantegen en la futura incorporació al sistema educatiu.

## Material didàctic per a totes les sessions

::: callout-tip
## Feu clic a cadascuna de les pestanyes per veure el material de cada sessió i treball asíncron
:::

::: panel-tabset
## Sessió 0 {.active}

<embed src="/files/sofesesion/SOFE-MEdu-sesion0.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 1

<embed src="/files/sofesesion/SOFE-MEdu-sesion1.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 2

<embed src="/files/sofesesion/SOFE-MEdu-sesion2.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 3

<embed src="/files/sofesesion/SOFE-MEdu-sesion3.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 4

<embed src="/files/sofesesion/SOFE-MEdu-sesion4.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 5

<embed src="/files/sofesesion/SOFE-MEdu-sesion5.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 6

<embed src="/files/sofesesion/SOFE-MEdu-sesion6.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 7

<embed src="/files/sofesesion/SOFE-MEdu-sesion7.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 8

<embed src="/files/sofesesion/SOFE-MEdu-sesion8.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 9

<embed src="/files/sofesesion/SOFE-MEdu-sesion9.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 10

<embed src="/files/sofesesion/SOFE-MEdu-sesion10.pdf" type="application/pdf" width="100%" height="800px"/>

## Tasca asíncrona 1

<embed src="/files/sofesesion/sofe-asincrona1.pdf" type="application/pdf" width="100%" height="800px"/>

## Tasca asíncrona 2

<embed src="/files/sofesesion/sofe-asincrona2.pdf" type="application/pdf" width="100%" height="800px"/>

## Tasca asíncrona 3

<embed src="/files/sofesesion/sofe-asincrona3.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Referències

-   [Professor Gencat](https://educacio.gencat.cat/ca/serveis-tramits/treballa-amb-nosaltres/opositions/personal-docent/){target="_blank"}

-   [Boles de treball de personal docent](https://educacio.gencat.cat/ca/serveis-tramits/treballa-amb-nosaltres/borses-treball/personal-interi-docent/){target="_blank"}

-   [Bolsa de treball de l'escola catalana](https://www.agrescat.cat/ca/borsa-treball.htm){target="_blank"}

-   [FECCT - Borsa de treball](https://www.fecc.cat/borsa-fecc/){target="_blank"}

## Vídeo per a la professora d'espanyol Clauda Comes Peña de l'Institut Ausias March de Barcelona

{{< video https://www.youtube.com/watch?v=pXchSFHB5uA aspect-ratio="4x3" >}}

## Documentació complementària aportada pel professor Lluís Pagès

::: panel-tabset
## Resum dels tipus de centres educatius {.active}

<embed src="/files/sofedocs/sofe-tipos-centros-edu.pdf" type="application/pdf" width="100%" height="800px"/>

## Funcions de les organitzacions educatives

<embed src="/files/sofedocs/sofe-doc-funciones-org-edu.pdf" type="application/pdf" width="100%" height="800px"/>

## Tractament de l'ús de les llengües

<embed src="/files/sofedocs/pec_tractament_us_llengues.pdf" type="application/pdf" width="100%" height="800px"/>

## Objectius del sistema educatiu

<embed src="/files/sofedocs/pec_objectius_projecte.pdf" type="application/pdf" width="100%" height="800px"/>

## Documents de gestió del centre

<embed src="/files/sofedocs/pec_documents_gestio.pdf" type="application/pdf" width="100%" height="800px"/>

## Competències del professorat

<embed src="/files/sofedocs/marc_competencies_professionals_docents_2024.pdf" type="application/pdf" width="100%" height="800px"/>

## Habilitats per ensenyar

<embed src="/files/sofedocs/nuevas-competencias-ensenar.pdf" type="application/pdf" width="100%" height="800px"/>

## Guia d'observació - Practicum

<embed src="/files/sofedocs/sofe-practicum-preguntes-guia-observacio.pdf" type="application/pdf" width="100%" height="800px"/>

## Plans educatius ambientals

<embed src="/files/sofedocs/marc_pee_xtec.pdf" type="application/pdf" width="100%" height="800px"/>


## UNESCO - contracte social per a l'educació

<embed src="/files/sofedocs/cat_reimaginem-junts-els-nostres-futurs.pdf" type="application/pdf" width="100%" height="800px"/>

:::


