---
title: "Assignatura: Societat, Família i Educació"
subtitle: "Processos i contextos educatius"
filename: sofe-inicio
author: "Pedro Martinez Duran"
date: "15/11/2025"
date-modified: last-modified
date-format: full
description: Fonaments organitzatius i psicopedagògics de la funció educativa a la comunitat catalana
categories: [marc educatiu, projecte educatiu, sistema educatiu]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

* Aquesta assignatura aborda els fonaments organitzatius i psicopedagògics de la funció educativa a la comunitat catalana. D'una banda, presenta el sistema educatiu, els centres educatius on es desenvolupa l'activitat (instituts, instituts escolars, centres de formació professional, centres de formació d'adults, escoles oficials d'idiomes i altres) i la seva interrelació amb l'entorn familiar i social, incidint en la concepció actual de l'ensenyament-aprenentatge i els diferents perfils de l'alumnat (edat, desenvolupament cognitiu, aspecte sociocultural i econòmic). S'hi inclouen aspectes com les funcions i deures del professor i de l'aprenent, l'accés a l'exercici de la funció docent o les principals característiques organitzatives dels centres (departaments de disciplines o matèries, professorat, coordinació, cicles d'avaluació, etc.).

* D'altra banda, també se centra en la gestió diària de l'aula, posant èmfasi en l'organització de la docència i de les classes, l'adaptació del currículum al centre i a cada grup d'alumnes, l'articulació dels recursos tecnològics, l'orientació educativa i l'acció tutorial, la promoció del benestar de l'alumnat i la prevenció i atenció de la violència i la personalització dels aprenentatges. Es tracta de conèixer tant l'organització estructural, funcional i normativa de l'educació secundària com de saber facilitar la convivència entre els diferents agents i saber preveure i resoldre els conflictes.

* L'assignatura no pressuposa coneixements previs de l'alumne, sinó que pretén aprofitar l'experiència personal prèvia com a alumne (a secundària, batxillerat, etc.) i fins i tot com a professor ocasional (substitut, classes particulars, etc.). Així mateix, davant els ràpids canvis socials i tecnològics que s'estan produint en els darrers anys, aquesta assignatura pretén oferir eines pràctiques i reflexions a partir de casos reals per preparar millor l'alumnat per al present canviant i el futur imprevist.

* L'assignatura té un valor de 10 ECTS, que suposa 260 hores de treball de l'estudiant, amb 30 sessions presencials de dues hores (60 hores), impartides en modalitat presencial i virtual síncrona i asíncrona. S'ensenya, sobretot, abans de fer la segona visita al centre, quan hauràs de fer classes, per tal de dotar-te de tots els coneixements i habilitats necessàries per fer-ho bé.

<br>

## Informació tècnica

* **Codi de l'assignatura:** 32865

* **Temps:**
  - Jornada completa: primer semestre
  - Jornada parcial: primer any, anual

* **Nombre de crèdits:** 10 ECTS

* **Dedicació:** 250 hores (60 hores de classe: 40 presencials i 20 virtuals asíncrones)

* **Professor responsable:** Sílvia Marro i Teresa Martínez (coordinadors) i Lluís Pagès

<br>

## Preguntes clau

Algunes de les preguntes que podreu respondre al final d'aquesta assignatura són:

* Com es defineix el sistema educatiu català i quines són les seves prioritats?

* Quins són els principals tipus de centres educatius catalans, quines característiques té cadascun d'ells, com es distribueixen i quins recursos té cadascun?

* Com s'accedeix a l'exercici de la funció docent?

* Quins són els meus deures i drets com a professor?

* Com concreta i desplega un centre el seu projecte educatiu?

* Quina és l'estructura i el funcionament d'un centre educatiu?

* Com fomenten els centres educatius la participació de la comunitat educativa i les relacions amb l'entorn?

* Com es promou la innovació educativa? Quins programes, projectes i pràctiques es desenvolupen per promoure la innovació als centres educatius?

* Com poden els centres educatius garantir el benestar dels alumnes i com prevenen i tracten la violència?

* Quines són les principals característiques dels estudiants adolescents, adults i el seu aprenentatge?

* Quins recursos tinc disponibles per atendre la diversitat dels alumnes i com els puc utilitzar?

* Quines característiques ha de tenir la tutoria dels estudiants per ser eficaç?

* Com podem donar una resposta educativa als alumnes amb NESE?

* Com podem dissenyar la personalització de l'aprenentatge per als estudiants?

<br>

## Mòduls d'assignatures

Els mòduls que conformen aquesta assignatura són aquests, amb les modalitats corresponents:

* **Marc educatiu**, en modalitat presencial i asíncrona.

* **Projecte educatiu**, presencial i modalitat asíncrona.

<br>

## Gols

* Conèixer el marc normatiu, organitzatiu i de funcionament dels centres.

* Comprendre i assumir les funcions i responsabilitats educatives que exerceix el professor.

* Desenvolupar habilitats socials i adquirir eines professionals per col·laborar amb els equips docents i la direcció del centre i per relacionar-se amb les famílies i les entitats de l'entorn.

* Valorar els processos d'interacció i comunicació a l'aula i al centre per afavorir la convivència i el benestar de l'alumnat.

* Determinar les mesures de suport educatiu necessàries per dissenyar estratègies d'intervenció educativa adequades.

* Relacionar l'educació formal amb l'entorn sociocultural i els espais d'aprenentatge informal, i amb el paper rellevant que tenen els entorns familiars i les entitats socials en l'educació dels joves.

<br>

## Competències

* Desenvolupar estratègies d'interacció per poder col·laborar amb els diferents agents dins i fora del centre.

* Comprendre l'organització i el funcionament del centre i saber integrar-s'hi.

* Saber analitzar les necessitats específiques dels alumnes per prevenir les dificultats d'aprenentatge.

* Conèixer els diferents recursos educatius segons les necessitats de l'alumnat.

* Guiar itineraris educatius: conèixer recursos i estratègies per facilitar la continuïtat dels estudis.

<br>

## Continguts

* Prioritats dels sistemes educatius al segle XXI. El sistema educatiu català.

* Tipologia de centres educatius i recursos del sistema educatiu.

* Accés a l'exercici de la funció docent. Competències, funcions, drets i deures del professor. La funció docent.

* Organització i funcionament del centre educatiu. L'autonomia del centre.

* Projecte Educatiu de Centre. Projecte lingüístic de centre.

* Participació de la comunitat educativa: estratègies i òrgans de participació. Relacions del centre amb l'entorn.

* Innovació en educació i transformació educativa. Programes, projectes i pràctiques. Programes específics. Plans d'acció.

* El benestar dels alumnes. Abordar la violència.

* Aprenentatge i desenvolupament en les diferents etapes educatives.

* Característiques de l'alumnat en les diferents etapes educatives.

* El currículum a les diferents etapes educatives. Habilitats transversals.

* Personalització de l'aprenentatge i atenció a tot l'alumnat en el marc d'un sistema educatiu inclusiu. Inclusió versus atenció a la diversitat. Mides i suports. Plans individualitzats.

* Necessitats específiques de suport educatiu (NESE).

* Acció tutorial, orientació educativa i orientació professional.

* La interacció entre alumnes. Aspectes psicosocials de l'aprenentatge.

* Interacció amb equips docents (psicopedagogs, suport lingüístic, aules d'acollida) i entitats del voltant.

<br>

## Avaluació

**Tasca 1.** Resolució d'un qüestionari de preguntes breus sobre el contingut de l'assignatura. **(50%)**

**Tasca 2.** Resolució d'un cas pràctic relacionat amb els continguts de l'assignatura. **(50%)**

<br>

## Recursos i bibliografia recomanada

Baudrit, A. (2012) Interacció entre estudiants. Quan l'ajuda mútua enriqueix el coneixement. Madrid: Marcea.

Castellana, M. (2003) La relació de l'adolescent amb persones significatives. Barcelona: P.A.U. Educació.

Coll, C. (2004) "La construcció del coneixement a l'escola: cap al desenvolupament d'un marc global de referència per a l'educació a l'escola", dins C. Coll (coord). Psicologia de la Instrucció. Barcelona: UOC.

Coll, Cèsar. (2000) Psicologia de la docència: ensenyament i aprenentatge a l'educació secundària. Barcelona: Horsori-ICE UB.

Coll, C. (coord.). (2010). Desenvolupament, aprenentatge i ensenyament a l'Educació Secundària. Barcelona: Graó.

Departament d'Ensenyament (2017). Marc de la innovació pedagògica a Catalunya.

Departament d'Ensenyament (2023). Marc de competències professionals docents.

Departament d'Ensenyament (2023). Protocol d'actuació davant qualsevol tipus de violència en l'àmbit escolar.

Escaño, J. i M. Gil. (2008) "Motivació i esforç a l'educació secundària", a C. Coll (coord.). Desenvolupament, aprenentatge i ensenyament a l'Educació Secundària. Barcelona: Graó (pàgines 131-148).

Feixa, Carles. (2005) "Ser jove: avui, ahir, demà", a DDAA. Joventut i Valors, la clau de la societat del futur. Barcelona: Obra Social La Caixa.

Funes, J. (2003) "Claus per llegir l'adolescència". Quaderns de Pedagogia, 320, 46-51.

Funes, J. (2010) 9 idees clau. Educar en l'adolescència. Barcelona: Graó

Funes, J. (coord) (2004) Arguments adolescents. Barcelona: Fundació Bofill.

López, P. (2009) "Cervell, intel·ligències i dissenys d'ensenyament-aprenentatge". Perspectiva escolar, 333. Rosa Sensat.

López Vicente, P. (2008) Espais d'aprenentatge. Idees, estratègies i reflexions. Barcelona: MEGS.

Martí, E.; Onrubia, J. (coords.) (1997). Psicologia del desenvolupament. El món de l'adolescència. Barcelona: ICE/ Horsori (caps. II, III, V).

Martí, E.; Onrubia, Javier. (2004) "Teories de l'aprenentatge escolar", dins C. Coll (coord). Psicologia instructiva. pàg. 65-76. Barcelona: UOC.

Moreno, A. (2009) "Desenvolupament durant l'adolescència", dins A. Moreno (coord). Psicologia del desenvolupament II. Barcelona: UOC.

Perinat, A. et al. (1997) "Desenvolupament en l'adolescència", dins A. Perinat. Desenvolupament i aprenentatge en edat escolar. Barcelona: UOC.

Teixidó Saballs, J. (2001) "Ser professor de secundària, avui", Bloc del GROC: Grup de Recerca en Organització de Centres.

UNESCO (2015). Repensar l'educació: cap a un bé comú global?

UNESCO (2017). Manual per a entorns d'aprenentatge innovadors.

UNESCO (2022). Reimaginem el nostre futur junts. Un nou contracte social per a l'educació

Vaello Orts, J. (2007). Com ensenyar als que no volen. Madrid: Santillana.

**Diversa documentació i normativa** del Departament d'Ensenyament sobre els ensenyaments que intervenen en aquest màster: educació secundària (ESO i batxillerat), cicles formatius, formació d'adults i ensenyament d'idiomes.

<br>

## Mòdul: Marc Educatiu

**Professor:** Lluís Pagès

**Modalitat:** Presencial i asíncron

### Competència

* Saber integrar-se com a docent al sistema educatiu català, entendre el context particular que l'envolta i saber relacionar-se amb els diferents equips i agents socials, per complir amb èxit la funció educativa.

### Gols

* Conèixer les principals característiques del sistema educatiu català i del centre particular en el qual ens incorporem i saber desenvolupar una tasca eficaç que contribueixi a formar l'alumnat de manera satisfactòria.

* Conèixer la documentació i la normativa i saber aprofitar els diferents casos reals treballats en el màster per resoldre els reptes que es plantegen en la futura incorporació al sistema educatiu.

### Continguts i Activitats per Sessions

1. Prioritats dels sistemes educatius al segle XXI. El sistema educatiu català. Prioritats actuals.

2. Tipologia de centres educatius i recursos del sistema educatiu.

3. Accés a l'exercici de la funció docent. Funcions, drets i deures del professor. La funció docent.

4. Competències docents

5. Organització i funcionament del centre educatiu. Autonomia del centre.

6. Projecte Educatiu de Centre. Projecte lingüístic de centre.

7. Participació de la comunitat educativa: estratègies i òrgans de participació. Relacions del centre amb l'entorn.

8. Innovació en educació i transformació educativa. Programes, projectes i pràctiques. Programes específics. Plans d'acció.

9. El benestar dels alumnes.

10. Abordar la violència.

### Literatura

Normes i directrius educatives de cada ensenyament del Departament d'Ensenyament i Formació Professional i dels diferents agents socials implicats pel que fa als centres de secundària, centres de formació d'adults i escoles oficials d'idiomes.

<br>

## Mòdul: Projecte Educatiu

**Professades:** Sílvia Marro i Teresa Martínez

**Modalitat:** Presencial i asíncron

### Competència

* Saber identificar les principals característiques del centre educatiu en què ens incorporem com a docents, per tal de poder regular la nostra intervenció de la manera més adequada per a l'alumnat, els equips docents i tots els agents del centre.

### Gols

* Conèixer les característiques dels alumnes de les diferents etapes educatives (secundària obligatòria i postobligatòria).

* Promoure la personalització de l'aprenentatge i l'atenció a tot l'alumnat en el marc d'un sistema educatiu inclusiu. Mides i suports. Plans individualitzats.

* Conèixer i avaluar la resposta educativa en funció de les necessitats específiques de suport educatiu (NESE) de l'alumnat.

* Compartir estratègies d'acció tutorial, orientació educativa i orientació professional.

* Realitzar la coordinació amb els equips docents (psicopedagogs, suport lingüístic, aules d'acollida) i entitats del voltant.

### Continguts i Activitats

1. Aprenentatge i desenvolupament a l'adolescència.

2. Característiques de l'alumnat en les diferents etapes educatives.

3. Alumnes amb necessitats específiques de suport educatiu (NESE).

4. Personalització de l'aprenentatge i atenció a tot l'alumnat en el marc d'un sistema educatiu inclusiu.

5. La interacció entre alumnes. Aspectes psicosocials de l'aprenentatge.

### Literatura

Diversos exemples de Projecte Educatiu de Centre, Pla d'Acció Tutorial i Pla d'Orientació Educativa.

Cas pràctics de situacions reals o creïbles de tutoria, orientació educativa, atenció a la diversitat i la inclusió, actuació amb alumnes de NESE, conflictes escolars diversos, etc.
