---
title: "Anàlisi de CV"
subtitle: "Currículums de les especialitats de Ciències Naturals (Biologia i Geologia / Física i Química)"
filename: cfd-analisis-cv
author: "Pedro Martinez Duran"
date-modified: last-modified
date-format: full
description: Anàlisi dels currículums de les especialitats de Ciències Naturals (Biologia i Geologia / Física i Química)
categories: [anàlisi, CV, currículum]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> El professor Xavier Muñoz Báguena dirigeix ​​aquesta part del mòdul **Complements Formatius Disciplinaris** denominat **anàlisi dels currículums d'educació secundària**, amb els objectius de conèixer el pla d'estudis de ciències naturals d'ESO i batxillerat, reflexionant sobre els objectius d'ensenyament-aprenentatge de les ciències naturals a secundària (finalitats del currículum) i finalment proves externes d'anàlisi (4t d'ESO).

## Material de la sessió

::: callout-tip
## Feu clic a cadascuna de les pestanyes per veure el material de cada sessió
:::

::: panel-tabset
## Sessió 1 {.active}

<embed src="/files/CFD-analisis-CV.pdf" type="application/pdf" width="100%" height="800px"/>

## Decret 175/2022

<embed src="/files/Decret-CVE-DOGC.pdf" type="application/pdf" width="100%" height="800px"/>

## LOE+LOMLOE

<embed src="/files/loe-completa-con-lomloe.pdf" type="application/pdf" width="100%" height="800px"/>

## Avaluar per aprendre

<embed src="/files/avaluar_per_aprendre.pdf" type="application/pdf" width="100%" height="800px"/>

## Àrees prioritàries

<embed src="/files/CFD_ambitos-prioritarios.pdf" type="application/pdf" width="100%" height="800px"/>

## CV de competència a l'aula

<embed src="/files/CFD-CV-competencial-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## Recomanació CE

<embed src="/files/CFD_recomanacion-CE.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2024/25

::: panel-tabset
## Test de ciència 2024/25 {.active}

<embed src="/files/cfd-prova-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

## Full de respostes 2024/25

<embed src="/files/cfd-full-respostes-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2024/25

<embed src="/files/cfd-criteris-correccio-ciencia-2025.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2022/23

::: panel-tabset
## Prova de ciències 2022/23 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_22_23.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2022/23

<embed src="/files/provas-competencias-ct/Solucions/CBCT_22_23_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2022/23

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_22_23Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2020/21

::: panel-tabset
## Test de ciència 2020/21 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_20_21.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2020/21

<embed src="/files/provas-competencias-ct/Solucions/CBCT_20_21_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2020/21

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_20_21Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2019/20

::: panel-tabset
## Test de ciència 2019/20 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_19_20.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2019/20

<embed src="/files/provas-competencias-ct/Solucions/CBCT_19_20_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2019/20

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_19_20Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2018/19

::: panel-tabset
## Test de ciències 2018/19 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_18_19.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2018/19

<embed src="/files/provas-competencias-ct/Solucions/CBCT_18_19_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2018/19

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_18_19Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2017/18

::: panel-tabset
## Test de ciències 2017/18 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_17_18.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2017/18

<embed src="/files/provas-competencias-ct/Solucions/CBCT_17_18_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2017/18

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_17_18Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2016/17

::: panel-tabset
## Prova de ciències 2016/17 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_16_17.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2016/17

<embed src="/files/provas-competencias-ct/Solucions/CBCT_16_17_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2016/17

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_16_17Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Documentació de l'avaluació final de 4t d'ESO de competències científicotecnològiques 2015/16

::: panel-tabset
## Test de ciències 2015/16 {.active}

<embed src="/files/provas-competencias-ct/Proves/CBCT_15_16.pdf" type="application/pdf" width="100%" height="800px"/>

## Solucions 2015/16

<embed src="/files/provas-competencias-ct/Solucions/CBCT_15_16_Sol.pdf" type="application/pdf" width="100%" height="800px"/>

## Criteris de correcció 2015/16

<embed src="/files/provas-competencias-ct/Criteris_correccio/CBCT_15_16Cc.pdf" type="application/pdf" width="100%" height="800px"/>

:::

