---
title: "Geologia"
subtitle: "Guia integrada de l'especialitat de Ciències Naturals en Geologia"
filename: cfd-geologia
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Assignatura que abasta els aspectes específics del pla d'estudis de Geologia a l'educació secundària
categories: [accessoris, disciplina, geologia]
toc: true
number-sections: true

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> La professora Laia Ramon-Sala dirigeix ​​aquesta part del mòdul **Complements Formatius Disciplinaris** denominat **Geologia i Ciències Ambientals**, amb els objectius de conèixer el pla d'estudis de geologia i ciències ambientals d'ESO i batxillerat, i reflexionar sobre els objectius de l'ensenyament-aprenentatge de les ciències naturals a secundària.

## Material didàctic per a les sessions i el treball a realitzar

::: callout-tip
## Feu clic a cadascuna de les pestanyes per veure el material de la sessió inicial i la documentació associada al treball a realitzar
:::

::: {.panel-tabset}
## Sessió inicial {.active}

<embed src="/files/cfd-docs/cfd-geologia-intro.pdf" type="application/pdf" width="100%" height="800px"/>

## Bibliografia addicional

<embed src="/files/cfd-docs/cfd-geo-bibliografia.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Enllaços d'interès per al tema

- [Guia de roques del Museu de Ciències de Catalunya](https://museuciencies.cat/comunicacio/publicacions/divulgatives/guia-de-roques/)

- [Diccionari de geologia](https://cit.iec.cat/DGEOL/default.asp?opcio=0)

### RAPAKIVI - @jpereztar

{{< video https://www.youtube.com/watch?v=T2dbGA4vsEE aspect-ratio="4x3" >}}

### Himne de roca fòssil

{{< video https://youtu.be/ClJ5lwl_wM0 aspect-ratio="4x3" >}}


::: {.column-margin}
**Documentació de suport**

- [Any de prova de geologia 19/20](/files/cfd-docs/cfd-geo-geologia-provaA-competencia-geologica.pdf){.highlight width="10%" target="_blank"}

- [Prova de Geologia de correcció any 19/20](/files/cfd-docs/cfd-geo-geologia-provaA-correccion.pdf){.highlight width="10%" target="_blank"}

- [Any de prova de geologia 20/21](/files/cfd-docs/cfd-geo-prova-20-21.pdf){.highlight width="10%" target="_blank"}

- [Prova de correcció de geologia any 20/21](/files/cfd-docs/cfd-geo-correccion-prova-20-21.pdf){.highlight width="10%" target="_blank"}

- [Any de prova de geologia 21/22](/files/cfd-docs/cfd-geo-prova-21-22.pdf){.highlight width="10%" target="_blank"}

- [Prova de Geologia de correcció any 21/22](/files/cfd-docs/cfd-geo-correccion-prova-21-22.pdf){.highlight width="10%" target="_blank"}

:::

## Tasca 1 "Gaia, la gran mare"

En aquesta tasca es treballaran els següents objectius d'aprenentatge:

- Argumentar el coneixement dels diferents elements del sistema Terra, així com les interaccions entre ells a nivell local i global, per predir la dinàmica d'un sistema.

- Identificar situacions i explicar exemples de canvis paradigmàtics que han donat lloc a grans controvèrsies científiques en la història de la ciència.

Per aconseguir els objectius, mira els dos vídeos i realitza les tasques indicades, individualment. El primer té un caràcter narratiu adequat a un nivell d'ESO, fent la mateixa tasca. El segon té un caràcter purament didàctic i és força dens. Servirà per introduir o repassar conceptes clau en geologia, però fer aquesta activitat a l'aula seria massa pesat.

### Vídeo 1: Gaia, la gran mare

48' documental sobre l'origen, l'evolució i el futur de la Terra, amb èmfasi en els conceptes geològics i el paper de la vida i dels humans. Els fets i les idees es mostren mitjançant il·lustracions i animacions, així com pel·lícules fetes en llocs com museus i paisatges rellevants propers. També s'exposen les amenaces a la sostenibilitat del planeta. Hi ha tres tipus de preguntes:

- Preguntes que has de respondre abans de començar a veure el documental.

- Preguntes que has de respondre mentre veus el documental.

- Preguntes que has de respondre després de veure el documental.

Per aquest motiu tens unes dues hores per omplir el qüestionari, tot i que no he posat cap límit.

Després de veure el documental i contestar el qüestionari, fes una aportació a un dels debats del fòrum, tenint en compte el que han respost els teus companys.

{{< video https://youtu.be/OL6U_1WmBbw aspect-ratio="4x3" >}}

### Vídeo 2: Les profunditats de la Terra

Programa informatiu de 53' sobre la dinàmica interna del planeta, centrat en els fenòmens volcànics i sísmics, però també exposant la diferent composició de les capes de la Terra i el seu moviment. Els fets i les idees es mostren mitjançant animacions i models d'ensenyament analògic, així com pel·lícules fetes en llocs com museus i paisatges propers rellevants. Hi ha tres tipus de preguntes:

- Preguntes que has de respondre abans de començar a veure el programa informatiu.

- Preguntes que heu de respondre mentre visualitzeu el programa informatiu.

- Preguntes que has de respondre després de veure el programa informatiu.

[Veure programa informatiu: Les profunditats de la Terra](https://www.rtve.es/play/videos/curioseando/curioseando-t2-programa-5-profundidades-tierra/16444938/){target="_blank"}

## Tasca 2 "Minerals quotidians"

::: {.panel-tabset}
## Presentació inicial {.active}

<embed src="/files/cfd-docs/cfd-geo-minerals-quotidians.pdf" type="application/pdf" width="100%" height="800px"/>

## Activitat pràctica dels minerals quotidians

<embed src="/files/cfd-docs/cfd-tasca-minerals-quotidians.pdf" type="application/pdf" width="100%" height="800px"/>

:::

### Com funciona la terra - part 1

[Vegeu el vídeo: Com funciona la terra - part 1](file:///C:/Users/pedro/Documents/shared_VMs/Tasca2/view1.htm){target="_blank"}

### Com funciona la terra - part 2

[Vegeu el vídeo: Com funciona la terra - part 2](https://aulaglobal.upf.edu/mod/kalvidres/view.php?id=1665785){target="_blank"}


## Tasca 3 "El farciment i la seva litologia"

::: {.panel-tabset}
## Presentació inicial {.active}

<embed src="/files/cfd-docs/cfd-geo-presentacion-relleu.pdf" type="application/pdf" width="100%" height="800px"/>

## Què és la història geològica?

<embed src="/files/cfd-docs/cfd-geo-historia-geologica.pdf" type="application/pdf" width="100%" height="800px"/>

## Descripció de la tasca 3

<embed src="/files/cfd-docs/cfd-geo-tasca3-relleu.pdf" type="application/pdf" width="100%" height="800px"/>

:::

### El farciment geològic

[Veure el vídeo: El farciment geològic](https://aulaglobal.upf.edu/mod/kalvidres/view.php?id=1629089){target="_blank"}


## Tasca 4 "Interdependència - Notícies recents"

::: {.panel-tabset}
## Presentació inicial {.active}

<embed src="/files/cfd-docs/cfd-geo-relacion-tierra.pdf" type="application/pdf" width="100%" height="800px"/>

## Interdependència - Notícies recents

<embed src="/files/cfd-docs/cfd-geo-noticia-reciente.pdf" type="application/pdf" width="100%" height="800px"/>

:::





