---
title: "Pràctica de presentació de la situació d'aprenentatge"
subtitle: "Presentació de la situació d'aprenentatge"
filename: cfd-presentacion-tasca-cv
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Pràctica de presentació de la situació d'aprenentatge
categories: [presentació, accessoris, disciplina]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> Aquesta part és la pràctica de presentar l'enfocament d'una situació d'aprenentatge. El treball es basa en una tasca en grups de cinc components i a cada grup se li assignarà un curs i una assignatura d'ESO (Biologia i Geologia o Física i Química). El grup ha de decidir una situació d'aprenentatge adequada al nivell i matèria assignada. S'ha de presentar el context de la situació d'aprenentatge, així com indicar les competències específiques que considereu que es poden treballar. Marqueu també els criteris d'avaluació associats que serien aplicables i especifiqueu els coneixements de l'assignatura que es treballaria (Mapa conceptual). Observeu les possibles interaccions amb altres matèries que es puguin treballar de manera interdisciplinària. El producte final serà una presentació gravada a la qual apareixeran tots els membres del grup, que no haurà de superar els 12 minuts i es penjarà a la tasca corresponent al moodle CFD.

## Material pràctic de presentació de situacions d'aprenentatge

::: callout-tip
## Feu clic a cadascuna de les pestanyes per veure el material de pràctica
:::

::: panel-tabset
## Descripció de la pràctica {.active}

<embed src="/files/cfd-tasca-cv.pdf" type="application/pdf" width="100%" height="800px"/>

## Presentació de la pràctica

<embed src="/files/cfd-situacio-aprenentatge.pdf" type="application/pdf" width="100%" height="800px"/>

## Rúbrica d'avaluació

<embed src="/files/cfd-rubrica-tasca.pdf" type="application/pdf" width="100%" height="800px"/>

:::