---
title: "Teaching and Assessment"
subtitle: "Why, how, and what we evaluate"
filename: dae-evaluacion
author: "Pedro Martinez Duran"
date-modified: last-modified
date-format: full
description: Addressing the assessment of learning
categories: [assessment, learning, education]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentation

> Professor Laura Taberne leads this part of the development, learning, and education module called **teaching and assessment**, which addresses the assessment of learning. Traditionally, it has been understood as a tool for measuring students' academic success and assigning them a grade. This reductionist view has been progressively questioned from constructivist and competency-based pedagogical perspectives. Despite this, assessment is not obsolete; in fact, it is one of the most frequent, powerful, and decisive practices in any educational process.

::: callout-tip
## Click on each tab to view the material of each session
:::

::: panel-tabset
## Session 1 {.active}

<embed src="/files/S1_AVALUACIO_1.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 2

<embed src="/files/S2_AVALUACIO_2.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 3

<embed src="/files/S3_AVALUACIO_3.pdf" type="application/pdf" width="100%" height="800px"/>
:::

## References

-   [Gencat Evaluation ESO](https://xtec.gencat.cat/ca/curriculum/eso/avaluacio/)

-   [Gencat Tests of evaluation](https://projectes.xtec.cat/nou-curriculum/proves-davaluacio/)

-   [Gencat Agency of evaluation](https://avaluacioeducativa.gencat.cat/ca/avaluacions/)

-   [Gencat Evaluate to learn](https://xtec.gencat.cat/.content/alfresco/d/d/workspace/SpacesStore/0024/fc53024f-626e-423b-877a-932148c56075/avaluar_per_aprendre.pdf)