---
title: "Development, Learning and Education"
subtitle: "Classroom management, assessment and digital tools for science teaching"
filename: dae-inicio
author: "Pedro Martinez Duran"
date: "15/11/2025"
date-modified: last-modified
date-format: full
description: Subject that addresses the management of the face-to-face classroom, the evaluation of learning and the conception and management of digital tools
categories: [development, learning, education]
toc: true
number-sections: true
highlight-style: pygments
format: html
---

## Presentation

* This subject addresses three essential issues in the teaching-learning of natural sciences today in Catalonia, which are the management of a face-to-face classroom, the evaluation of learning and the conception and management of digital tools (inside the classroom, for formal teaching, and outside the classroom, for the continued education of the learner in their leisure contexts).

* The subject relates the most global psycho-pedagogical, normative and organizational contents, on a more macro or general level, treated in SOFE (Society, family and education: educational processes and contexts), with its correlation in more specific aspects, to a micro level, of the classroom and day-to-day life.

* The subject has a value of 5 ECTS, which represents 125 hours of student work, with 14 face-to-face sessions of two hours (28h), taught in face-to-face and synchronous virtual mode. It is taught above all before making the second visit to the center, when you will have to give classes, in order to equip you with all the knowledge and skills necessary to do it well.

<br>

## Technical Information

* **Subject code:** 32864

* **Timing:**
  - Full time: first semester
  - Part time: first year, first semester

* **Number of credits:** 5 ECTS

* **Dedication:** 125 hours (28 hours in person and 97 hours of autonomous work)

* **Teachers responsible for the subject:** Maria Calsamiglia, Arturo Cortés, Núria Domènech (coordinator), Laura Taberner and Lluís Terrado.

<br>

## Key Questions

Some of the questions that you will be able to answer at the end of this subject are:

* What is the role of teachers in building a good learning environment in the classroom?

* How to organize learning evaluation activities to promote an evaluation that combines regulatory and accreditation functions?

* What digital tools and methodologies are best for the design and application of classroom activities that promote the development of scientific competence in students?

<br>

## Subject Modules

The modules that make up this subject are these, with the corresponding modalities:

* **Teaching and evaluation**, in face-to-face and virtual synchronous mode.

* **Classroom management and cooperation**, in person.

* **Digital tools for scientific competence**, in face-to-face and synchronous virtual modes.

<br>

## Goals

* Know how to manage day-to-day life in the classroom, managing each group, managing classroom dynamics (time, space, instructions, interaction), the development of learning tasks and the anticipation and repair of conflicts.

* Know the main purposes, instruments and characteristics of evaluation and know how to implement them in a formative way in scientific education.

* Know and value the digital tools available at the center, know how to organize them effectively for all students, know how to choose the most suitable resources and educate students so that they can make instructive and effective use of these resources.

<br>

## Competencies

* Knowing how to adopt a perspective of inquiry in the classroom, to effectively and reflectively manage the dynamics and activities that are developed.

* Know how to identify the objective, characteristics, strengths and weaknesses and the usefulness of various evaluation instruments and know how to adapt them to each situation.

* Effectively use the center's digital tools for science class and know how to guide learners in the use of their digital resources inside and outside the classroom.

<br>

## Contents

* Classroom management strategies to build the bond with students, include routines and establish limits and tools to promote motivation.

* Functions of evaluation, main instruments and criteria to improve the regulation of teaching-learning.

* Digital tools inside and outside the classroom. Potentials and limitations. Uses. Apps and diverse use experiences.

<br>

## Assessment

* **Task 1.** Resolution of a practical case related to the contents of the classroom management and cooperation and teaching and evaluation modules. Individual resolution task (70%).

* **Task 2.** Digital Tools Module for Scientific Competence. Final report on the two case studies of the module (30%).

<br>

## Resources and Recommended Bibliography

AAVV. (2015) *Items released from scientific competition. PISA 2015* conceptual framework. Documents, 26. Publications of the Department of Education. Generalitat of Catalonia.

Barkley, E.F.; Cross, K.P.; Howell, C. (2007) *Collaborative learning techniques*, Madrid, Ed. Morata.

Cassany, Daniel. "How to evaluate?" in *Construct writing*. Barcelona: Paidós. 1999.

Francia, A., Mata, J., 2003. *Group dynamics and techniques*. CCS Publishing

González, Evaristo. (2020) "Educational transitions towards hybrid learning." Magisterium Magazine Portal. Madrid.

González, Evaristo. (2023) "Learning between university and non-university students with the 'case study' method." In: Edgar Loyola (coord.) *University student. Proposals and testimonials*. Cuenca (Ecuador). p. 11-31.

Jones, J. (2014) *What is new in AfL? A view from England, (UK)*. Unpublished manuscript: King's College London: University of London. Translated on the website of the Basic Skills Network.

Lemov, Doug. (2021) *Teach like a Champion. 3.0. 63 techniques that put students onto the path to college*. Jossey-bass INC

OECD (2017) *PISA Assessment and Analysis Framework for Development. Reading, math and science*. Organization for Economic Cooperation and Development.

Prensky, Mark. (2001) "Digital natives, digital immigrants", *On the horizon*, 9 (5), October 2001. MCB University Press.

Ruiz, Hector. (2021) *How do we learn? A scientific approach to learning and teaching*. Graó Editorial.

Pujolàs, P. Lago J. R. (Coordinators) (2014) *Cooperate to Learn/Learn to Cooperate. Implementation of cooperative learning in the classroom*. Publications University of Vic.

Sanmartí, Neus (2020). *Evaluate to learn*. General Directorate of Curriculum and Personalization. Publications of the Department of Education.

Sanmartí, N., León, M. (2021) *Evaluate and learn: a single process*. Ed. Octahedron

Scrivener, J. (2012) *Classroom Management Techniques*. Cambridge. Cambridge University Press.

Simón, M. et al. (2006) "Evaluation as a self-regulation process: ten years later." *Alembic: Didactics of experimental sciences*, No. 48 pages. 32-41.

Teixidó Saballs, J. (2001) "Being a secondary school teacher, today", GROC Blog: Research Group on Center Organization.

Vaello Orts, J. (2007). *How to teach those who don't want to class*. Madrid: Santillana.

Vaello Orts, J. (2003) *Conflict resolution in the classroom*. Santillana Educación, SL.

Vinagre, M. (2010) *Theory and practice of computer-assisted collaborative learning*. Madrid: Synthesis.

White, David and Alison Le Cornu. (2011) "Visitors and Residents: A new typology for online engagement", *First Monday*, 16 (9), September.

<br>

## Repositories

XTEC. Educational Telematics Network of Catalonia. Natural sciences. Project work.

WebQuestCat. Catalan Webquest Community.
