---
title: "Los objetivos de la secuencia didáctica I"
subtitle: "Programación, innovación y reflexión sobre la práctica docente en ciencias"
filename: deia-secuencia-didactica1
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Asignatura centrada en el diseño y evaluación de situaciones de aprendizaje y la investigación-acción en el aula
categories: [diseño, innovación, aprendizaje]
toc: true
number-sections: true

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentación

> El profesor Marcel Costa dirige esta parte del módulo de **Diseño de entornos de aprendizaje innovadores e iniciación en la investigación educativa de las ciencias naturales** denominado **de los objetivos a las secuencias didácticas I**, para dar relevancia a la definición de los objetivos de aprendizaje, el concepto de secuencias didácticas, su programación y ciclos de aprendizaje.

## Material didáctico de las sesiones y material de apoyo

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material didáctico de las sesiones y el material de apoyo
:::

::: {.column-margin}
**Documentación de apoyo**

- [A Model of Learning Objectives](/files/deia-docs/RevisedBloomsHandout.pdf){.highlight width="10%" target="_blank"}

- [Document de suport per a les programacions de les situacions d'aprenentatge ESO](/files/deia-docs/doc-support-ESO.pdf){.highlight width="10%" target="_blank"}

- [Document de suport per a les programacions de les situacions d'aprenentatge Batxillerat](/files/deia-docs/document_suport_BATXI.pdf){.highlight width="10%" target="_blank"}

- [Primer esbós d'una seqüència didàctica i dels seus objectius](/files/deia-docs/deia-sqd1/Fulldetreball3.2aelaboracióobjectiusViu-Inert1rESO.pdf){.highlight width="10%" target="_blank"}

- [Objectius i paraules clau - 2n ESO](/files/deia-docs/deia-sqd1/Fulldetreball3.2bobjectiusmescles-solucions2nESO.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - Batxillerat](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeBAT.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - CFGM-S](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeCFGM-S.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - ESO](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeESO.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - Atmosfera 1r ESO](/files/deia-docs/deia-sqd1/Programaciósituacióaprenentatgeatmosfera1rESO.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - Batxillerat](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaBAT.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - ESO](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaESO.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - ESO Atmosfera v2](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaESOatmosferav2.pdf){.highlight width="10%" target="_blank"}

- [Unitat meteo 2p1](/files/deia-docs/deia-sqd1/Unitatmeteo2p1.pdf){.highlight width="10%" target="_blank"}

:::

::: {.panel-tabset}
## Sesión 1 {.active}

<embed src="/files/deia-docs/deia-sesion1-sq.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/deia-docs/deia-sesion2-sq.pdf" type="application/pdf" width="100%" height="800px"/>

## Unidad didáctica 1 ESO. "Un clima que canvia – Actuem avui per garantir el demà"

<embed src="/files/deia-docs/Delgado_2017.pdf" type="application/pdf" width="100%" height="800px"/>

:::