---
title: "Iniciación a la innovación y la investigación educativa"
subtitle: "Programación, innovación y reflexión sobre la práctica docente en ciencias"
filename: deia-innovacion-inves-edu
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Asignatura centrada en dar a conocer qué es la práctica reflexiva y la investigación-acción. Se presentan algunas características de la observación al aula y algunos instrumentos para hacerlo durante el primer prácticum. Ademas se busca pensar en el propio punto de partida profesional, a partir de las vivencias y creencias cada uno de nosotros
categories: [diseño, innovación, aprendizaje, práctica reflexiva, investigación-acción, observación, aula]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentación

> El profesor Jordi Soler Garcia dirige esta parte del módulo de **Diseño de entornos de aprendizaje innovadores e iniciación en la investigación educativa de las ciencias naturales** denominado **inicio a la innovación y la investigación educativa**, para dar a conocer qué es la práctica reflexiva y la investigación-acción. Se presentan algunas características de la observación al aula y algunos instrumentos para hacerlo durante el primer practicum. Ademas se busca pensar en el propio punto de partida profesional, a partir de las vivencias y creencias cada uno de nosotros.

## Objetivos

- Conocer qué es la práctica reflexiva y la investigación-acción.
- Conocer los objetivos y el funcionamiento de la asignatura.
- Conocer algunas características de la observación al aula y algunos instrumentos para hacerlo durante el primer prácticum

## Material didáctico de las sesiones y material de apoyo

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material didáctico de las sesiones y el material de apoyo
:::

::: column-margin
**Documentación de apoyo**

[Bases metodològiques per a la recerca educativa](/files/deia-docs/bases-metodologiques-fulldetreball.pdf){.highlight width="10%" target="_blank"}

[Guia del portafoli del practicum](/files/deia-docs/guia-portafoli.pdf){.highlight width="10%" target="_blank"}

:::

::: panel-tabset
## Sesión 1 {.active}

<embed src="/files/deia-docs/deia-sesion1-innov.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/deia-docs/deia-sesion2-innov.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 3

<embed src="/files/deia-docs/deia-sesion3-innov.pdf" type="application/pdf" width="100%" height="800px"/>

:::