---
title: "Práctica de la presentación de la situación de aprendizaje"
subtitle: "Presentación de la situación de aprendizaje"
filename: cfd-presentacion-tasca-cv
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Práctica de la presentación de la situación de aprendizaje
categories: [presentación, complementos, disciplinar]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentación

> Esta parte es la práctica de la presentación del planteamiento de una situación de aprendizaje. El trabajo se basa en una tarea en grupos de cinco componentes y a cada grupo le será asignado un curso y una materia de la ESO (Biología y Geología o Física y Química). El grupo tiene que decidir una situación de aprendizaje adecuada al nivel y la materia asignada. Hay que presentar el contexto de la situación de aprendizaje, así como indicar las competencias específicas que considera que pueden ser trabajadas. También marcar los criterios de evaluación asociados que serían de aplicación y concretar los saberes de la materia que se trabajarían (Mapa conceptual). Apuntar posibles interacciones con otras materias que puedan ser trabajadas interdisciplinariamente. El producto final será una presentación grabada a la cual aparezcan todos los miembros del grupo, que no tendrá que superar los 12 minutos y que se colgará a la tarea correspondiente del moodle de CFD.

## Material de la práctica de la presentación de la situación de aprendizaje

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de la práctica
:::

::: {.panel-tabset}
## Descripción de la práctica {.active}

<embed src="/files/cfd-docs/cfd-tasca-cv.pdf" type="application/pdf" width="100%" height="800px"/>

## Presentación de la práctica

<embed src="/files/cfd-docs/cfd-situacio-aprenentatge.pdf" type="application/pdf" width="100%" height="800px"/>

## Rubrica de evaluación

<embed src="/files/cfd-docs/cfd-rubrica-tasca.pdf" type="application/pdf" width="100%" height="800px"/>

:::