---
title: "Els objectius de la seqüència didàctica I"
subtitle: "Programació, innovació i reflexió sobre la pràctica docent en ciència"
filename: deia-secuencia-didactica1
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Assignatura centrada en el disseny i avaluació de situacions d'aprenentatge i recerca-acció a l'aula
categories: [disseny, innovació, aprenentatge]
toc: true
number-sections: true

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> El professor Marcel Costa dirigeix ​​aquesta part del mòdul **Disseny d'entorns innovadors d'aprenentatge i iniciació a la recerca educativa en ciències naturals** denominat **des d'objectius a seqüències didàctiques I**, per donar rellevància a la definició dels objectius d'aprenentatge, al concepte de seqüències didàctiques, a la seva programació i cicles d'aprenentatge.

## Material didàctic per a les sessions i material de suport

::: callout-tip
## Cliqueu a cadascuna de les pestanyes per veure el material didàctic de les sessions i el material de suport
:::

::: {.column-margin}
**Documentació de suport**

- [Un model d'objectius d'aprenentatge](/files/deia-docs/RevisedBloomsHandout.pdf){.highlight width="10%" target="_blank"}

- [Document de suport a la programació de les situacions d'aprenentatge de l'ESO](/files/deia-docs/doc-support-ESO.pdf){.highlight width="10%" target="_blank"}

- [Document de suport per a la programació de les situacions d'aprenentatge Batxillerat](/files/deia-docs/document_suport_BATXI.pdf){.highlight width="10%" target="_blank"}

- [Primer esquema d'una seqüència didàctica i els seus diferents objectes](/files/deia-docs/deia-sqd1/Fulldetreball3.2aelaboracióobjectiusViu-Inert1rESO.pdf){.highlight width="10%" target="_blank"}

- [Objectius i paraules clau - 2n ESO](/files/deia-docs/deia-sqd1/Fulldetreball3.2bobjectiusmescles-solucions2nESO.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - Batxillerat](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeBAT.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - CFGM-S](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeCFGM-S.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - ESO](/files/deia-docs/deia-sqd1/ProgramaciósituacióaprenentatgeESO.pdf){.highlight width="10%" target="_blank"}

- [Programació situació aprenentatge - Atmosfera 1r ESO](/files/deia-docs/deia-sqd1/Programaciósituacióaprenentatgeatmosfera1rESO.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - Batxillerat](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaBAT.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - ESO](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaESO.pdf){.highlight width="10%" target="_blank"}

- [Programació unitat didàctica - ESO Atmosfera v2](/files/deia-docs/deia-sqd1/ProgramacióunitatdidàcticaESOatmosferav2.pdf){.highlight width="10%" target="_blank"}

- [Unitat meteo 2p1](/files/deia-docs/deia-sqd1/Unitatmeteo2p1.pdf){.highlight width="10%" target="_blank"}

:::

::: {.panel-tabset}
## Sessió 1 {.active}

<embed src="/files/deia-docs/deia-sesion1-sq.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 2

<embed src="/files/deia-docs/deia-sesion2-sq.pdf" type="application/pdf" width="100%" height="800px"/>

## Unitat didàctica 1 ESO. "Un clima canviant: actua aquí per garantir la resta"

<embed src="/files/deia-docs/Delgado_2017.pdf" type="application/pdf" width="100%" height="800px"/>

:::