---
title: "Ensenyament i Avaluació"
subtitle: "Perquè, com i que avaluem"
filename: dae-evaluacion
author: "Pedro Martinez Duran"
date-modified: last-modified
date-format: full
description: Asignatura que aborda la evaluació dels aprenentatges
categories: [evaluacio, aprenentatge, educacio]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentació

> La professora Laura Taberne dirigeix aquesta part del mòdul de desenvolupament, aprenentatge i educació denominat *ensenyament i avaluació*, on s'aborda l'avaluació dels aprenentatges. Tradicionalment, s'ha entès com un instrument per a mesurar l'èxit acadèmic de l'alumnat i assignar-li una qualificació. Aquesta visió reduccionista ha estat progressivament qüestionada des de les perspectives pedagògiques constructivistes i competencials. Malgrat això, l'avaluació no està obsoleta, de fet és una de les pràctiques més freqüents, potents i decisives en qualsevol procés educatiu.

::: callout-tip
## Fes clic en cadascuna de les pestanyes per a visualitzar el material de cada sessió
:::

::: panel-tabset
## Sessió 1 {.active}

<embed src="/files/S1_AVALUACIO_1.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 2

<embed src="/files/S2_AVALUACIO_2.pdf" type="application/pdf" width="100%" height="800px"/>

## Sessió 3

<embed src="/files/S3_AVALUACIO_3.pdf" type="application/pdf" width="100%" height="800px"/>
:::

## Referències

-   [Gencat Avaluació ESO](https://xtec.gencat.cat/ca/curriculum/eso/avaluacio/){target="_blank"}

-   [Gencat Proves d'avaluació](https://projectes.xtec.cat/nou-curriculum/proves-davaluacio/){target="_blank"}

-   [Gencat Agència d'avaluació](https://avaluacioeducativa.gencat.cat/ca/avaluacions/){target="_blank"}

-   [Gencat Avaluar per a aprendre](https://xtec.gencat.cat/.content/alfresco/d/d/workspace/SpacesStore/0024/fc53024f-626e-423b-877a-932148c56075/avaluar_per_aprendre.pdf){target="_blank"}