---
title: "Educational framework"
subtitle: "Context and regulations of the Catalan educational system"
filename: sofe-marco-educativo
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Context and regulations of the Catalan educational system for teachers who join the Catalan educational system, with emphasis on the legal framework and job opportunities
categories: [education, educational system, regulations, teaching, employment, training, higher education, educational policy]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentation

> Professor Lluís Pagès directs this part of the **society, family and education: educational processes and contexts** module called **educational framework**, which addresses how to join the Catalan educational system as a teacher, understanding the particular context that surrounds it and knowing how to interact with the various teams and social agents, to successfully fulfill the educational function. This implies knowing the main characteristics of the Catalan educational system and the particular center in which we join and knowing how to develop an effective task that contributes to educating students in a satisfactory manner. In addition, know the documentation and regulations and know how to take advantage of the various real cases worked on in the master's degree to resolve the challenges that arise in future incorporation into the educational system.

## Didactic material for all sessions

::: callout-tip
## Click on each of the tabs to view the material of each session and asynchronous work
:::

::: panel-tabset
## Session 0 {.active}

<embed src="/files/sofesesion/SOFE-MEdu-sesion0.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 1

<embed src="/files/sofesesion/SOFE-MEdu-sesion1.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 2

<embed src="/files/sofesesion/SOFE-MEdu-sesion2.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 3

<embed src="/files/sofesesion/SOFE-MEdu-sesion3.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 4

<embed src="/files/sofesesion/SOFE-MEdu-sesion4.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 5

<embed src="/files/sofesesion/SOFE-MEdu-sesion5.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 6

<embed src="/files/sofesesion/SOFE-MEdu-sesion6.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 7

<embed src="/files/sofesesion/SOFE-MEdu-sesion7.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 8

<embed src="/files/sofesesion/SOFE-MEdu-sesion8.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 9

<embed src="/files/sofesesion/SOFE-MEdu-sesion9.pdf" type="application/pdf" width="100%" height="800px"/>

## Session 10

<embed src="/files/sofesesion/SOFE-MEdu-sesion10.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous task 1

<embed src="/files/sofesesion/sofe-asincrona1.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous task 2

<embed src="/files/sofesesion/sofe-asincrona2.pdf" type="application/pdf" width="100%" height="800px"/>

## Asynchronous task 3

<embed src="/files/sofesesion/sofe-asincrona3.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## References

-   [Gencat Teaching staff](https://educacio.gencat.cat/ca/serveis-tramits/treballa-amb-nosaltres/opositions/personal-docent/){target="_blank"}

-   [Teaching staff job boards](https://educacio.gencat.cat/ca/serveis-tramits/treballa-amb-nosaltres/borses-treball/personal-interi-docent/){target="_blank"}

-   [Catalan school job board](https://www.agrescat.cat/ca/borsa-treball.htm){target="_blank"}

-   [FECCT - Job Board](https://www.fecc.cat/borsa-fecc/){target="_blank"}

## Video to Spanish teacher Clauda Comes Peña from the Ausias March Institute in Barcelona

{{< video https://www.youtube.com/watch?v=pXchSFHB5uA aspect-ratio="4x3" >}}

## Additional documentation provided by Professor Lluís Pagès

::: panel-tabset
## Summary of educational center types {.active}

<embed src="/files/sofedocs/sofe-tipos-centros-edu.pdf" type="application/pdf" width="100%" height="800px"/>

## Functions of educational organizations

<embed src="/files/sofedocs/sofe-doc-funciones-org-edu.pdf" type="application/pdf" width="100%" height="800px"/>

## Treatment of the use of languages

<embed src="/files/sofedocs/pec_tractament_us_llengues.pdf" type="application/pdf" width="100%" height="800px"/>

## Objectives of the educational system

<embed src="/files/sofedocs/pec_objectius_projecte.pdf" type="application/pdf" width="100%" height="800px"/>

## Center management documents

<embed src="/files/sofedocs/pec_documents_gestio.pdf" type="application/pdf" width="100%" height="800px"/>

## Teacher competencies

<embed src="/files/sofedocs/marc_competencies_professionals_docents_2024.pdf" type="application/pdf" width="100%" height="800px"/>

## Skills to teach

<embed src="/files/sofedocs/nuevas-competencias-ensenar.pdf" type="application/pdf" width="100%" height="800px"/>

## Observation guide - Practicum

<embed src="/files/sofedocs/sofe-practicum-preguntes-guia-observacio.pdf" type="application/pdf" width="100%" height="800px"/>

## Environmental educational plans

<embed src="/files/sofedocs/marc_pee_xtec.pdf" type="application/pdf" width="100%" height="800px"/>


## UNESCO - social contract for education

<embed src="/files/sofedocs/cat_reimaginem-junts-els-nostres-futurs.pdf" type="application/pdf" width="100%" height="800px"/>

:::


