---
title: "Introduction to Society, Family and Education"
subtitle: "Educational processes and contexts"
filename: sofe-inicio
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Organizational and psychopedagogical foundations of the educational function in the Catalan community
categories: [educational framework, educational project, educational system]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentation

* This subject addresses the organizational and psycho-pedagogical foundations of the educational function in the Catalan community. On the one hand, it presents the educational system, the educational centers in which the activity takes place (institutes, school institutes, centers that provide vocational training, adult training centers, official language schools and others) and their interrelation with the family and social environment, influencing the current conception of teaching-learning and the various profiles of the students (age, cognitive development, sociocultural and economic aspects). Aspects are included such as the functions and duties of the teacher and the apprentice, access to the exercise of the teaching function or the main organizational features of the centers (departments of disciplines or subjects, teaching staff, coordination, evaluation cycles, etc.).

* On the other hand, it also focuses on the daily management of the classroom, emphasizing the organization of teaching and classes, the adaptation of the curriculum to the center and each group of students, the articulation of technological resources, educational guidance and tutorial action, the promotion of student well-being and the prevention and attention of violence and personalization of learning. It is about knowing both the structural, functional and regulatory organization of secondary education as well as knowing how to facilitate coexistence between the various agents and knowing how to foresee and resolve conflicts.

* The subject does not presuppose prior knowledge of the student, but hopes to take advantage of previous personal experience as a student (in secondary school, high school, etc.) and even as an occasional teacher (substitute, private classes, etc.). Also, given the rapid social and technological changes that are occurring in recent years, this subject hopes to offer practical tools and reflections based on real cases to better prepare students for the changing present and unforeseen future.

* The subject has a value of 10 ECTS, which represents 260 hours of student work, with 30 face-to-face sessions of two hours (60 hours), taught in face-to-face and virtual synchronous and asynchronous mode. It is taught, above all, before making the second visit to the center, when you will have to take classes, in order to equip you with all the knowledge and skills necessary to do it well.


## Technical Information

* **Subject code:** 32865

* **Timing:**
  - Full time: first semester
  - Part time: first year, annual

* **Number of credits:** 10 ECTS

* **Dedication:** 250 hours (60 hours of class: 40 in-person and 20 asynchronous virtual)

* **Responsible teacher:** Sílvia Marro and Teresa Martínez (coordinators) and Lluís Pagès


## Key Questions

Some of the questions that you will be able to answer at the end of this subject are:

* How is the Catalan educational system defined and what are its priorities?

* What are the main types of Catalan educational centers, what features does each of them have, how are they distributed and what resources does each one have?

* How do you access the exercise of the teaching function?

* What are my duties and rights as a teacher?

* How does a center specify and deploy its educational project?

* What is the structure and operation of an educational center?

* How do educational centers encourage the participation of the educational community and relationships with the environment?

* How is educational innovation promoted? What programs, projects and practices are developed to promote innovation in educational centers?

* How can educational centers guarantee the well-being of students and how do they prevent and treat violence?

* What are the main characteristics of adolescent students, adults and their learning?

* What resources do I have available to address the diversity of students and how can I use them?

* What characteristics should student tutoring have to be effective?

* How can we provide an educational response to students with NESE?

* How can we design personalization of learning for students?



## Subject Modules

The modules that make up this subject are these, with the corresponding modalities:

* **Educational framework**, in face-to-face and asynchronous mode.

* **Educational project**, in person and asynchronous mode.



## Goals

* Know the regulatory, organizational and operating framework of the centers.

* Understand and assume the educational functions and responsibilities exercised by a teacher.

* Develop social skills and acquire professional tools to collaborate with the teaching teams and the center management and to interact with families and surrounding entities.

* Assess the interaction and communication processes in the classroom and at the center to promote coexistence and well-being of the students.

* Determine the educational support measures necessary to design appropriate educational intervention strategies.

* Relate formal education to the sociocultural environment and informal learning spaces, and to the relevant role played by family environments and social entities in the education of young people.



## Competencies

* Develop interaction strategies to be able to collaborate with the various agents inside and outside the center.

* Understand the organization and operation of the center and know how to integrate into it.

* Know how to analyze the specific needs of students to prevent learning difficulties.

* Know the various educational resources according to the needs of the students.

* Guide educational itineraries: know resources and strategies to facilitate the continuity of studies.



## Contents

* Priorities of educational systems in the 21st century. The Catalan educational system.

* Typology of educational centers and resources of the educational system.

* Access to the exercise of the teaching function. Competencies, functions, rights and duties of the teacher. The teaching function.

* Organization and operation of the educational center. The autonomy of the center.

* Center Educational Project. Center linguistic project.

* Participation of the educational community: strategies and participation bodies. Relationships of the center with the environment.

* Innovation in education and educational transformation. Programs, projects and practices. Specific programs. Action plans.

* The well-being of the students. Addressing violence.

* Learning and development in the different educational stages.

* Characteristics of the students in the different educational stages.

* The curriculum at different educational stages. Transversal skills.

* Personalization of learning and attention to all students within the framework of an inclusive educational system. Inclusion versus attention to diversity. Measurements and supports. Individualized plans.

* Specific educational support needs (NESE).

* Tutorial action, educational guidance and professional guidance.

* The interaction between students. Psychosocial aspects of learning.

* Interaction with teaching teams (psychopedagogues, linguistic support, reception classrooms) and surrounding entities.



## Assessment

**Task 1.** Resolution of a questionnaire of short questions about the content of the subject. **(50%)**

**Task 2.** Resolution of a practical case related to the contents of the subject. **(50%)**


## Resources and Recommended Bibliography

Baudrit, A. (2012) Interaction between students. When mutual help enriches knowledge. Madrid: Marcea.

Castellana, M. (2003) The adolescent's relationship with significant people. Barcelona: P.A.U. Education.

Coll, C. (2004) "The construction of knowledge at school: towards the development of a global framework of reference for education at school", in C. Coll (coord). Instructional Psychology. Barcelona: UOC.

Coll, Caesar. (2000) Instructional psychology: teaching and learning in secondary education. Barcelona: Horsori-ICE UB.

Coll, C. (coord.). (2010). Development, learning and teaching in Secondary Education. Barcelona: Graó.

Department of Education (2017). Framework of pedagogical innovation in Catalonia.

Department of Education (2023). Framework of professional teaching competencies.

Department of Education (2023). Action protocol for any type of violence in the school environment.

Escaño, J. and M. Gil. (2008) "Motivation and effort in secondary education", in C. Coll (coord.). Development, learning and teaching in Secondary Education. Barcelona: Graó (pages 131-148).

Feixa, Carles. (2005) "Being young: today, yesterday, tomorrow", in DDAA. Youth and Values, the key to the society of the future. Barcelona: Obra Social La Caixa.

Funes, J. (2003) "Keys to reading adolescence." Pedagogy Notebooks, 320, 46-51.

Funes, J. (2010) 9 key ideas. Educate in adolescence. Barcelona: Graó

Funes, J. (coord) (2004) Adolescent arguments. Barcelona: Bofill Foundation.

López, P. (2009) "Brain, intelligences and teaching-learning designs." School perspective, 333. Rosa Sensat.

López Vicente, P. (2008) Learning spaces. Ideas, strategies and reflections. Barcelona: MEGS.

Martí, E.; Onrubia, J. (coords.) (1997). Developmental psychology. The Teenage World. Barcelona: ICE/ Horsori (chaps. II, III, V).

Martí, E.; Onrubia, Javier. (2004) "Theories of school learning", in C. Coll (coord). Instructional psychology. p. 65-76. Barcelona: UOC.

Moreno, A. (2009) "Development during adolescence", in A. Moreno (coord). Developmental psychology II. Barcelona: UOC.

Perinat, A. et al. (1997) "Development in adolescence", in A. Perinat. Development and learning during school age. Barcelona: UOC.

Teixidó Saballs, J. (2001) "Being a secondary school teacher, today", GROC Blog: Research Group on Center Organization.

UNESCO (2015). Rethinking education: towards a global common good?

UNESCO (2017). Manual for innovative learning environments.

UNESCO (2022). Let's reimagine our futures together. A new social contract for education

Vaello Orts, J. (2007). How to teach those who don't want to. Madrid: Santillana.

**Various documentation and regulations** from the Department of Education regarding the teachings involved in this master's degree: secondary education (ESO and baccalaureate), training cycles, adult training and language teaching.



## Module: Educational Framework

**Teacher:** Lluís Pagès

**Modality:** In-person and asynchronous

### Competence

* Knowing how to join the Catalan educational system as a teacher, understanding the particular context that surrounds it and knowing how to interact with the various teams and social agents, to successfully fulfill the educational function.

### Goals

* Know the main characteristics of the Catalan educational system and the particular center in which we join and know how to develop an effective task that contributes to educating students in a satisfactory manner.

* Know the documentation and regulations and know how to take advantage of the various real cases worked on in the master's degree to resolve the challenges that arise in future incorporation into the educational system.

### Contents and Activities by Sessions

1. Priorities of educational systems in the 21st century. The Catalan educational system. Current priorities.

2. Typology of educational centers and resources of the educational system.

3. Access to the exercise of the teaching function. Functions, rights and duties of the teacher. The teaching function.

4. Teaching competencies

5. Organization and operation of the educational center. Center autonomy.

6. Center Educational Project. Center linguistic project.

7. Participation of the educational community: strategies and participation bodies. Relationships of the center with the environment.

8. Innovation in education and educational transformation. Programs, projects and practices. Specific programs. Action plans.

9. The well-being of the students.

10. Addressing violence.

### Literature

Regulations and educational guidelines for each teaching of the Department of Education and Vocational Training and the various social agents involved with regard to secondary schools, adult training centers and official language schools.



## Module: Educational Project

**Teachers:** Sílvia Marro and Teresa Martínez

**Modality:** In-person and asynchronous

### Competence

* Knowing how to identify the main characteristics of the educational center in which we join as teachers, in order to be able to regulate our intervention in the most appropriate way for the students, the teaching teams and all the agents of the center.

### Goals

* Know the characteristics of students in the different educational stages (compulsory secondary and post-compulsory).

* Promote the personalization of learning and attention to all students within the framework of an inclusive educational system. Measurements and supports. Individualized plans.

* Know and assess the educational response based on the specific educational support needs (NESE) of the students.

* Share strategies for tutorial action, educational guidance and professional guidance.

* Carry out coordination with teaching teams (psychopedagogues, linguistic support, reception classrooms) and surrounding entities.

### Contents and Activities

1. Learning and development in adolescence.

2. Characteristics of the students in the different educational stages.

3. Students with specific educational support needs (NESE).

4. Personalization of learning and attention to all students within the framework of an inclusive educational system.

5. The interaction between students. Psychosocial aspects of learning.

### Literature

Various examples of Center Educational Project, Tutorial Action Plan and Educational Guidance Plan.

Case studies of real or credible situations of tutoring, educational guidance, attention to diversity and inclusivity, action with NESE students, various school conflicts, etc.
