---
title: "Gestión del ambiente de aprendizaje en el aula"
subtitle: "Gestión del aula a través del vínculo, rutinas, límites y motivación"
filename: dae-gestion-aula
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Asignatura que aborda la gestión del ambiente de aprendizaje en el aula a través del vínculo, rutinas, límites y motivación
categories: [gestión, ambiente, aprendizaje, vínculo, rutinas, límites, motivación]
toc: true
number-sections: true

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentación

> Los profesores Artur Cortés y Lluís Terrado dirigen esta parte del módulo de desarrollo, aprendizaje y educación denominado **gestión del ambiente de aprendizaje en el aula**, donde se aborda la gestión del ambiente de aprendizaje en el aula a través de las cuatro grandes áreas sobre las que se pueden incidir para construir un buen ambiente de aprendizaje: vínculo, rutinas, límites y motivación.

## Material didáctico de todas las sesiones

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de cada sesión
:::

::: {.panel-tabset}
## Sesión 1 {.active}

<embed src="/files/dae-docs/Sesion1-gestion-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/dae-docs/Sesion2-gestion-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 3

<embed src="/files/dae-docs/Sesion3-gestion-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 4

<embed src="/files/dae-docs/Sesion4-gestion-aula.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 5

<embed src="/files/dae-docs/Sesion5_Gestion del Aula_Motivacion.pdf" type="application/pdf" width="100%" height="800px"/>

## Rúbrica del trabajo final

<embed src="/files/dae-docs/SesionRubrica-gestion-aula.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Referencias

-   [Gencat Gestionar la aula](https://projectes.xtec.cat/tilc/elements-tilc/com-ensenyar/gestionar-laula/){target="_blank"}

-   [Gencat Documentación de gestión de aula](https://xtec.gencat.cat/.content/alfresco/d/d/workspace/SpacesStore/0064/92789ee1-c500-45a1-970c-5064478f1316/12_Gestio_aula.pdf){target="_blank"}

-   [Gencat Estructura y gestion de recursos en el aula](https://xtec.gencat.cat/web/.content/centres/projeducatiu/convivencia/aplicacio/graella-estructura-gestio-recursos-aula.pdf){target="_blank"}
