---
title: "Enseñanza y Evaluación"
subtitle: "Por que, como y que evaluamos"
filename: dae-evaluacion
author: "Pedro Martínez Durán"
date-modified: last-modified
date-format: full
description: Asignatura que aborda la evaluación de los aprendizajes
categories: [evaluación, aprendizaje, educación]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Presentación

> La profesora Laura Taberne dirige esta parte del módulo de desarrollo, aprendizaje y educación denominado **enseñanza y evaluación**, donde se aborda la evaluación de los aprendizajes. Tradicionalmente, se ha entendido como un instrumento para medir el éxito académico del alumnado y asignarle una calificación. Esta visión reduccionista ha sido progresivamente cuestionada desde las perspectivas pedagógicas constructivistas y competenciales. A pesar de esto, la evaluación no está obsoleta, de hecho es una de las prácticas más frecuentes, potentes y decisivas en cualquier proceso educativo.

## Material didáctico de todas las sesiones

::: callout-tip
## Haz click en cada una de las pestañas para visualizar el material de cada sesión
:::

::: panel-tabset
## Sesión 1 {.active}

<embed src="/files/S1_AVALUACIO_1.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 2

<embed src="/files/S2_AVALUACIO_2.pdf" type="application/pdf" width="100%" height="800px"/>

## Sesión 3

<embed src="/files/S3_AVALUACIO_3.pdf" type="application/pdf" width="100%" height="800px"/>

## Evaluar para aprender

<embed src="/files/avaluar_per_aprendre.pdf" type="application/pdf" width="100%" height="800px"/>

:::

## Referencias

-   [Gencat Evaluación ESO](https://xtec.gencat.cat/ca/curriculum/eso/avaluacio/){target="_blank"}

-   [Gencat Pruebas de evaluación](https://projectes.xtec.cat/nou-curriculum/proves-davaluacio/){target="_blank"}

-   [Gencat Agencia de evaluación](https://avaluacioeducativa.gencat.cat/ca/avaluacions/){target="_blank"}


