---
title: "Plantilla d'observació a l'aula"
subtitle: "Eina de seguiment i avaluació de l'alumnat"
filename: plantilla-observacion-aula
author: "Pedro Martínez"
date-modified: last-modified
date-format: full
description: Plantilla completa per a l'observació sistemàtica dels alumnes a l'aula
categories: [pràctica, observació, aula]
toc: true
number-sections: true
highlight-style: pygments
lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false
format: html
---

## Dades d'observador i classe

<ul style="list-style-type: none;">
  <li>
    <strong>Nombre del observador:</strong>
    <input type="text" name="nombre_observador" placeholder="Nombre completo" style="width: 200px">
  </li>
  <br>
  <li>
    <strong>Fecha de observación:</strong>
    <input type="date" name="fecha_observacion" style="width: 200px">
  </li>
  <br>
  <li>
    <strong>Curso:</strong>
    <input type="text" name="curso" placeholder="curso del aula" style="width: 200px">
  </li>
  <br>
  <li>
    <strong>Asignatura:</strong>
    <input type="text" name="asignatura" placeholder="asignatura del aula" style="width: 200px">
  </li>
  <br>
  <li>
    <strong>Numero de Alumnos:</strong>
    <input type="number" name="numero_alumnos" min="0" max="100" placeholder="Numero de Alumnos" style="width: 200px">
  </li>
  <br>
  <li>
    <strong>Hora:</strong>
    <input type="text" name="hora" placeholder="Hora de observación" style="width: 200px">
  </li>
</ul>

## Clima i comportament general a l'aula
### Clima emocional de l'aula
<ul>
  <li>
    Entorn de respecte i confiança entre els alumnes:
    <input type="checkbox" name="clima_respeto" value="1">1
    <input type="checkbox" name="clima_respeto" value="2">2
    <input type="checkbox" name="clima_respeto" value="3">3
    <input type="checkbox" name="clima_respeto" value="4">4
    <input type="checkbox" name="clima_respeto" value="5">5
    <input type="checkbox" name="clima_respeto" value="6">6
    <input type="checkbox" name="clima_respeto" value="7">7
    <input type="checkbox" name="clima_respeto" value="8">8
    <input type="checkbox" name="clima_respeto" value="9">9
    <input type="checkbox" name="clima_respeto" value="10">10
  </li>
  <li>
    Nivell de tensió o conflicte observat:
    <input type="checkbox" name="clima_tension" value="1">1
    <input type="checkbox" name="clima_tension" value="2">2
    <input type="checkbox" name="clima_tension" value="3">3
    <input type="checkbox" name="clima_tension" value="4">4
    <input type="checkbox" name="clima_tension" value="5">5
    <input type="checkbox" name="clima_tension" value="6">6
    <input type="checkbox" name="clima_tension" value="7">7
    <input type="checkbox" name="clima_tension" value="8">8
    <input type="checkbox" name="clima_tension" value="9">9
    <input type="checkbox" name="clima_tension" value="10">10
  </li>
  <li>
    Actitud general davant l'activitat docent:
    <input type="checkbox" name="clima_actitud" value="1">1
    <input type="checkbox" name="clima_actitud" value="2">2
    <input type="checkbox" name="clima_actitud" value="3">3
    <input type="checkbox" name="clima_actitud" value="4">4
    <input type="checkbox" name="clima_actitud" value="5">5
    <input type="checkbox" name="clima_actitud" value="6">6
    <input type="checkbox" name="clima_actitud" value="7">7
    <input type="checkbox" name="clima_actitud" value="8">8
    <input type="checkbox" name="clima_actitud" value="9">9
    <input type="checkbox" name="clima_actitud" value="10">10
  </li>
</ul>

### Disciplina i normes
<ul>
  <li>
    Compliment de les normes de convivència:
    <input type="checkbox" name="cumplimiento_normas" value="1">1
    <input type="checkbox" name="cumplimiento_normas" value="2">2
    <input type="checkbox" name="cumplimiento_normas" value="3">3
    <input type="checkbox" name="cumplimiento_normas" value="4">4
    <input type="checkbox" name="cumplimiento_normas" value="5">5
    <input type="checkbox" name="cumplimiento_normas" value="6">6
    <input type="checkbox" name="cumplimiento_normas" value="7">7
    <input type="checkbox" name="cumplimiento_normas" value="8">8
    <input type="checkbox" name="cumplimiento_normas" value="9">9
    <input type="checkbox" name="cumplimiento_normas" value="10">10
  </li>
  <li>
    Interrupcions i interrupcions durant la sessió:
    <input type="checkbox" name="interrupciones" value="1">1
    <input type="checkbox" name="interrupciones" value="2">2
    <input type="checkbox" name="interrupciones" value="3">3
    <input type="checkbox" name="interrupciones" value="4">4
    <input type="checkbox" name="interrupciones" value="5">5
    <input type="checkbox" name="interrupciones" value="6">6
    <input type="checkbox" name="interrupciones" value="7">7
    <input type="checkbox" name="interrupciones" value="8">8
    <input type="checkbox" name="interrupciones" value="9">9
    <input type="checkbox" name="interrupciones" value="10">10
  </li>
  <li>
    Necessitat de trucades d'atenció del professor:
    <input type="checkbox" name="llamadas_atencion" value="1">1
    <input type="checkbox" name="llamadas_atencion" value="2">2
    <input type="checkbox" name="llamadas_atencion" value="3">3
    <input type="checkbox" name="llamadas_atencion" value="4">4
    <input type="checkbox" name="llamadas_atencion" value="5">5
    <input type="checkbox" name="llamadas_atencion" value="6">6
    <input type="checkbox" name="llamadas_atencion" value="7">7
    <input type="checkbox" name="llamadas_atencion" value="8">8
    <input type="checkbox" name="llamadas_atencion" value="9">9
    <input type="checkbox" name="llamadas_atencion" value="10">10
  </li>
  <li>
    Puntualitat a l'inici i al final de les activitats:
    <input type="checkbox" name="puntualidad" value="1">1
    <input type="checkbox" name="puntualidad" value="2">2
    <input type="checkbox" name="puntualidad" value="3">3
    <input type="checkbox" name="puntualidad" value="4">4
    <input type="checkbox" name="puntualidad" value="5">5
    <input type="checkbox" name="puntualidad" value="6">6
    <input type="checkbox" name="puntualidad" value="7">7
    <input type="checkbox" name="puntualidad" value="8">8
    <input type="checkbox" name="puntualidad" value="9">9
    <input type="checkbox" name="puntualidad" value="10">10
  </li>
</ul>

### Interaccions socials
<ul>
  <li>
    Qualitat de les relacions entre alumnes:
    <input type="checkbox" name="relaciones" value="1">1
    <input type="checkbox" name="relaciones" value="2">2
    <input type="checkbox" name="relaciones" value="3">3
    <input type="checkbox" name="relaciones" value="4">4
    <input type="checkbox" name="relaciones" value="5">5
    <input type="checkbox" name="relaciones" value="6">6
    <input type="checkbox" name="relaciones" value="7">7
    <input type="checkbox" name="relaciones" value="8">8
    <input type="checkbox" name="relaciones" value="9">9
    <input type="checkbox" name="relaciones" value="10">10
  </li>
  <li>
    Col·laboració espontània entre companys:
    <input type="checkbox" name="colaboracion" value="1">1
    <input type="checkbox" name="colaboracion" value="2">2
    <input type="checkbox" name="colaboracion" value="3">3
    <input type="checkbox" name="colaboracion" value="4">4
    <input type="checkbox" name="colaboracion" value="5">5
    <input type="checkbox" name="colaboracion" value="6">6
    <input type="checkbox" name="colaboracion" value="7">7
    <input type="checkbox" name="colaboracion" value="8">8
    <input type="checkbox" name="colaboracion" value="9">9
    <input type="checkbox" name="colaboracion" value="10">10
  </li>
  <li>
    Inclusió de tot l'alumnat en la dinàmica:
    <input type="checkbox" name="inclusion" value="1">1
    <input type="checkbox" name="inclusion" value="2">2
    <input type="checkbox" name="inclusion" value="3">3
    <input type="checkbox" name="inclusion" value="4">4
    <input type="checkbox" name="inclusion" value="5">5
    <input type="checkbox" name="inclusion" value="6">6
    <input type="checkbox" name="inclusion" value="7">7
    <input type="checkbox" name="inclusion" value="8">8
    <input type="checkbox" name="inclusion" value="9">9
    <input type="checkbox" name="inclusion" value="10">10
  </li>
  <li>
    Actituds d'ajuda mútua observades:
    <input type="checkbox" name="ayuda_mutua" value="1">1
    <input type="checkbox" name="ayuda_mutua" value="2">2
    <input type="checkbox" name="ayuda_mutua" value="3">3
    <input type="checkbox" name="ayuda_mutua" value="4">4
    <input type="checkbox" name="ayuda_mutua" value="5">5
    <input type="checkbox" name="ayuda_mutua" value="6">6
    <input type="checkbox" name="ayuda_mutua" value="7">7
    <input type="checkbox" name="ayuda_mutua" value="8">8
    <input type="checkbox" name="ayuda_mutua" value="9">9
    <input type="checkbox" name="ayuda_mutua" value="10">10
  </li>
</ul>

## Rendiment acadèmic i compromís
### Nivell d'atenció i concentració
<ul>
  <li>
    Percentatge estimat d'alumnes atents:
    <input type="checkbox" name="estudiantes_atentos" value="1">1
    <input type="checkbox" name="estudiantes_atentos" value="2">2
    <input type="checkbox" name="estudiantes_atentos" value="3">3
    <input type="checkbox" name="estudiantes_atentos" value="4">4
    <input type="checkbox" name="estudiantes_atentos" value="5">5
    <input type="checkbox" name="estudiantes_atentos" value="6">6
    <input type="checkbox" name="estudiantes_atentos" value="7">7
    <input type="checkbox" name="estudiantes_atentos" value="8">8
    <input type="checkbox" name="estudiantes_atentos" value="9">9
    <input type="checkbox" name="estudiantes_atentos" value="10">10
  </li>
  <li>
    Dispersió o distraccions freqüents:
    <input type="checkbox" name="dispersion" value="1">1
    <input type="checkbox" name="dispersion" value="2">2
    <input type="checkbox" name="dispersion" value="3">3
    <input type="checkbox" name="dispersion" value="4">4
    <input type="checkbox" name="dispersion" value="5">5
    <input type="checkbox" name="dispersion" value="6">6
    <input type="checkbox" name="dispersion" value="7">7
    <input type="checkbox" name="dispersion" value="8">8
    <input type="checkbox" name="dispersion" value="9">9
    <input type="checkbox" name="dispersion" value="10">10
  </li>
  <li>
    Capacitat de mantenir l'atenció durant les explicacions:
    <input type="checkbox" name="foco" value="1">1
    <input type="checkbox" name="foco" value="2">2
    <input type="checkbox" name="foco" value="3">3
    <input type="checkbox" name="foco" value="4">4
    <input type="checkbox" name="foco" value="5">5
    <input type="checkbox" name="foco" value="6">6
    <input type="checkbox" name="foco" value="7">7
    <input type="checkbox" name="foco" value="8">8
    <input type="checkbox" name="foco" value="9">9
    <input type="checkbox" name="foco" value="10">10
  </li>
</ul>

### Participació activa
<ul>
  <li>
    Freqüència de les intervencions voluntàries:
    <input type="checkbox" name="intervenciones" value="1">1
    <input type="checkbox" name="intervenciones" value="2">2
    <input type="checkbox" name="intervenciones" value="3">3
    <input type="checkbox" name="intervenciones" value="4">4
    <input type="checkbox" name="intervenciones" value="5">5
    <input type="checkbox" name="intervenciones" value="6">6
    <input type="checkbox" name="intervenciones" value="7">7
    <input type="checkbox" name="intervenciones" value="8">8
    <input type="checkbox" name="intervenciones" value="9">9
    <input type="checkbox" name="intervenciones" value="10">10
  </li>
  <li>
    Qualitat de les aportacions realitzades:
    <input type="checkbox" name="aportaciones" value="1">1
    <input type="checkbox" name="aportaciones" value="2">2
    <input type="checkbox" name="aportaciones" value="3">3
    <input type="checkbox" name="aportaciones" value="4">4
    <input type="checkbox" name="aportaciones" value="5">5
    <input type="checkbox" name="aportaciones" value="6">6
    <input type="checkbox" name="aportaciones" value="7">7
    <input type="checkbox" name="aportaciones" value="8">8
    <input type="checkbox" name="aportaciones" value="9">9
    <input type="checkbox" name="aportaciones" value="10">10
  </li>
  <li>
    Diversitat dels alumnes participants:
    <input type="checkbox" name="diversidad_participantes" value="1">1
    <input type="checkbox" name="diversidad_participantes" value="2">2
    <input type="checkbox" name="diversidad_participantes" value="3">3
    <input type="checkbox" name="diversidad_participantes" value="4">4
    <input type="checkbox" name="diversidad_participantes" value="5">5
    <input type="checkbox" name="diversidad_participantes" value="6">6
    <input type="checkbox" name="diversidad_participantes" value="7">7
    <input type="checkbox" name="diversidad_participantes" value="8">8
    <input type="checkbox" name="diversidad_participantes" value="9">9
    <input type="checkbox" name="diversidad_participantes" value="10">10
  </li>
  <li>
    Resposta a les preguntes del professor:
    <input type="checkbox" name="respuesta_docente" value="1">1
    <input type="checkbox" name="respuesta_docente" value="2">2
    <input type="checkbox" name="respuesta_docente" value="3">3
    <input type="checkbox" name="respuesta_docente" value="4">4
    <input type="checkbox" name="respuesta_docente" value="5">5
    <input type="checkbox" name="respuesta_docente" value="6">6
    <input type="checkbox" name="respuesta_docente" value="7">7
    <input type="checkbox" name="respuesta_docente" value="8">8
    <input type="checkbox" name="respuesta_docente" value="9">9
    <input type="checkbox" name="respuesta_docente" value="10">10
  </li>
</ul>

### Motivació i interès

<ul>
  <li>
    Actitud davant els continguts treballats:
    <input type="checkbox" name="actitud_contenidos" value="1">1
    <input type="checkbox" name="actitud_contenidos" value="2">2
    <input type="checkbox" name="actitud_contenidos" value="3">3
    <input type="checkbox" name="actitud_contenidos" value="4">4
    <input type="checkbox" name="actitud_contenidos" value="5">5
    <input type="checkbox" name="actitud_contenidos" value="6">6
    <input type="checkbox" name="actitud_contenidos" value="7">7
    <input type="checkbox" name="actitud_contenidos" value="8">8
    <input type="checkbox" name="actitud_contenidos" value="9">9
    <input type="checkbox" name="actitud_contenidos" value="10">10
  </li>
  <li>
    Implicació amb les activitats proposades:
    <input type="checkbox" name="engagement" value="1">1
    <input type="checkbox" name="engagement" value="2">2
    <input type="checkbox" name="engagement" value="3">3
    <input type="checkbox" name="engagement" value="4">4
    <input type="checkbox" name="engagement" value="5">5
    <input type="checkbox" name="engagement" value="6">6
    <input type="checkbox" name="engagement" value="7">7
    <input type="checkbox" name="engagement" value="8">8
    <input type="checkbox" name="engagement" value="9">9
    <input type="checkbox" name="engagement" value="10">10
  </li>
  <li>
    Expressions de curiositat o preguntes:
    <input type="checkbox" name="curiosidad" value="1">1
    <input type="checkbox" name="curiosidad" value="2">2
    <input type="checkbox" name="curiosidad" value="3">3
    <input type="checkbox" name="curiosidad" value="4">4
    <input type="checkbox" name="curiosidad" value="5">5
    <input type="checkbox" name="curiosidad" value="6">6
    <input type="checkbox" name="curiosidad" value="7">7
    <input type="checkbox" name="curiosidad" value="8">8
    <input type="checkbox" name="curiosidad" value="9">9
    <input type="checkbox" name="curiosidad" value="10">10
  </li>
  <li>
    Resistència o apatia observada:
    <input type="checkbox" name="apatia" value="1">1
    <input type="checkbox" name="apatia" value="2">2
    <input type="checkbox" name="apatia" value="3">3
    <input type="checkbox" name="apatia" value="4">4
    <input type="checkbox" name="apatia" value="5">5
    <input type="checkbox" name="apatia" value="6">6
    <input type="checkbox" name="apatia" value="7">7
    <input type="checkbox" name="apatia" value="8">8
    <input type="checkbox" name="apatia" value="9">9
    <input type="checkbox" name="apatia" value="10">10
  </li>
</ul>

### Treball i esforç
<ul>
  <li>
    Ritme de treball durant les activitats individuals o grupals:
    <input type="checkbox" name="ritmo_trabajo" value="1">1
    <input type="checkbox" name="ritmo_trabajo" value="2">2
    <input type="checkbox" name="ritmo_trabajo" value="3">3
    <input type="checkbox" name="ritmo_trabajo" value="4">4
    <input type="checkbox" name="ritmo_trabajo" value="5">5
    <input type="checkbox" name="ritmo_trabajo" value="6">6
    <input type="checkbox" name="ritmo_trabajo" value="7">7
    <input type="checkbox" name="ritmo_trabajo" value="8">8
    <input type="checkbox" name="ritmo_trabajo" value="9">9
    <input type="checkbox" name="ritmo_trabajo" value="10">10
  </li>
  <li>
    Compliment de les tasques assignades:
    <input type="checkbox" name="cumplimiento_tareas" value="1">1
    <input type="checkbox" name="cumplimiento_tareas" value="2">2
    <input type="checkbox" name="cumplimiento_tareas" value="3">3
    <input type="checkbox" name="cumplimiento_tareas" value="4">4
    <input type="checkbox" name="cumplimiento_tareas" value="5">5
    <input type="checkbox" name="cumplimiento_tareas" value="6">6
    <input type="checkbox" name="cumplimiento_tareas" value="7">7
    <input type="checkbox" name="cumplimiento_tareas" value="8">8
    <input type="checkbox" name="cumplimiento_tareas" value="9">9
    <input type="checkbox" name="cumplimiento_tareas" value="10">10
  </li>
  <li>
    Ús productiu del temps de classe:
    <input type="checkbox" name="uso_tiempo" value="1">1
    <input type="checkbox" name="uso_tiempo" value="2">2
    <input type="checkbox" name="uso_tiempo" value="3">3
    <input type="checkbox" name="uso_tiempo" value="4">4
    <input type="checkbox" name="uso_tiempo" value="5">5
    <input type="checkbox" name="uso_tiempo" value="6">6
    <input type="checkbox" name="uso_tiempo" value="7">7
    <input type="checkbox" name="uso_tiempo" value="8">8
    <input type="checkbox" name="uso_tiempo" value="9">9
    <input type="checkbox" name="uso_tiempo" value="10">10
  </li>
  <li>
    Perseverança davant les dificultats:
    <input type="checkbox" name="perseverancia" value="1">1
    <input type="checkbox" name="perseverancia" value="2">2
    <input type="checkbox" name="perseverancia" value="3">3
    <input type="checkbox" name="perseverancia" value="4">4
    <input type="checkbox" name="perseverancia" value="5">5
    <input type="checkbox" name="perseverancia" value="6">6
    <input type="checkbox" name="perseverancia" value="7">7
    <input type="checkbox" name="perseverancia" value="8">8
    <input type="checkbox" name="perseverancia" value="9">9
    <input type="checkbox" name="perseverancia" value="10">10
  </li>
</ul>

## Gestió i organització de l'aula

### gestió del temps
<ul>
  <li>
    Ús efectiu del temps d'ensenyament:
    <input type="checkbox" name="aprovechamiento_tiempo" value="1">1
    <input type="checkbox" name="aprovechamiento_tiempo" value="2">2
    <input type="checkbox" name="aprovechamiento_tiempo" value="3">3
    <input type="checkbox" name="aprovechamiento_tiempo" value="4">4
    <input type="checkbox" name="aprovechamiento_tiempo" value="5">5
    <input type="checkbox" name="aprovechamiento_tiempo" value="6">6
    <input type="checkbox" name="aprovechamiento_tiempo" value="7">7
    <input type="checkbox" name="aprovechamiento_tiempo" value="8">8
    <input type="checkbox" name="aprovechamiento_tiempo" value="9">9
    <input type="checkbox" name="aprovechamiento_tiempo" value="10">10
  </li>
  <li>
    Transicions suaus entre activitats:
    <input type="checkbox" name="transiciones" value="1">1
    <input type="checkbox" name="transiciones" value="2">2
    <input type="checkbox" name="transiciones" value="3">3
    <input type="checkbox" name="transiciones" value="4">4
    <input type="checkbox" name="transiciones" value="5">5
    <input type="checkbox" name="transiciones" value="6">6
    <input type="checkbox" name="transiciones" value="7">7
    <input type="checkbox" name="transiciones" value="8">8
    <input type="checkbox" name="transiciones" value="9">9
    <input type="checkbox" name="transiciones" value="10">10
  </li>
  <li>
    Compliment de la planificació planificada:
    <input type="checkbox" name="planificacion" value="1">1
    <input type="checkbox" name="planificacion" value="2">2
    <input type="checkbox" name="planificacion" value="3">3
    <input type="checkbox" name="planificacion" value="4">4
    <input type="checkbox" name="planificacion" value="5">5
    <input type="checkbox" name="planificacion" value="6">6
    <input type="checkbox" name="planificacion" value="7">7
    <input type="checkbox" name="planificacion" value="8">8
    <input type="checkbox" name="planificacion" value="9">9
    <input type="checkbox" name="planificacion" value="10">10
  </li>
</ul>

### Organització espacial
<ul>
  <li>
    Adequació de la distribució del mobiliari:
    <input type="checkbox" name="distribucion_mobiliario" value="1">1
    <input type="checkbox" name="distribucion_mobiliario" value="2">2
    <input type="checkbox" name="distribucion_mobiliario" value="3">3
    <input type="checkbox" name="distribucion_mobiliario" value="4">4
    <input type="checkbox" name="distribucion_mobiliario" value="5">5
    <input type="checkbox" name="distribucion_mobiliario" value="6">6
    <input type="checkbox" name="distribucion_mobiliario" value="7">7
    <input type="checkbox" name="distribucion_mobiliario" value="8">8
    <input type="checkbox" name="distribucion_mobiliario" value="9">9
    <input type="checkbox" name="distribucion_mobiliario" value="10">10
  </li>
  <li>
    Accessibilitat i mobilitat a l'espai:
    <input type="checkbox" name="accesibilidad" value="1">1
    <input type="checkbox" name="accesibilidad" value="2">2
    <input type="checkbox" name="accesibilidad" value="3">3
    <input type="checkbox" name="accesibilidad" value="4">4
    <input type="checkbox" name="accesibilidad" value="5">5
    <input type="checkbox" name="accesibilidad" value="6">6
    <input type="checkbox" name="accesibilidad" value="7">7
    <input type="checkbox" name="accesibilidad" value="8">8
    <input type="checkbox" name="accesibilidad" value="9">9
    <input type="checkbox" name="accesibilidad" value="10">10
  </li>
  <li>
    Ús de diferents espais de l'aula:
    <input type="checkbox" name="uso_zonas" value="1">1
    <input type="checkbox" name="uso_zonas" value="2">2
    <input type="checkbox" name="uso_zonas" value="3">3
    <input type="checkbox" name="uso_zonas" value="4">4
    <input type="checkbox" name="uso_zonas" value="5">5
    <input type="checkbox" name="uso_zonas" value="6">6
    <input type="checkbox" name="uso_zonas" value="7">7
    <input type="checkbox" name="uso_zonas" value="8">8
    <input type="checkbox" name="uso_zonas" value="9">9
    <input type="checkbox" name="uso_zonas" value="10">10
  </li>
</ul>

### Ús de recursos i materials
<ul>
  <li>
    Disponibilitat i accés als materials necessaris:
    <input type="checkbox" name="disponibilidad_materiales" value="1">1
    <input type="checkbox" name="disponibilidad_materiales" value="2">2
    <input type="checkbox" name="disponibilidad_materiales" value="3">3
    <input type="checkbox" name="disponibilidad_materiales" value="4">4
    <input type="checkbox" name="disponibilidad_materiales" value="5">5
    <input type="checkbox" name="disponibilidad_materiales" value="6">6
    <input type="checkbox" name="disponibilidad_materiales" value="7">7
    <input type="checkbox" name="disponibilidad_materiales" value="8">8
    <input type="checkbox" name="disponibilidad_materiales" value="9">9
    <input type="checkbox" name="disponibilidad_materiales" value="10">10
  </li>
  <li>
    Ús de tecnologia (si escau):
    <input type="checkbox" name="uso_tecnologia" value="1">1
    <input type="checkbox" name="uso_tecnologia" value="2">2
    <input type="checkbox" name="uso_tecnologia" value="3">3
    <input type="checkbox" name="uso_tecnologia" value="4">4
    <input type="checkbox" name="uso_tecnologia" value="5">5
    <input type="checkbox" name="uso_tecnologia" value="6">6
    <input type="checkbox" name="uso_tecnologia" value="7">7
    <input type="checkbox" name="uso_tecnologia" value="8">8
    <input type="checkbox" name="uso_tecnologia" value="9">9
    <input type="checkbox" name="uso_tecnologia" value="10">10
  </li>
  <li>
    Ordre i cura del material:
    <input type="checkbox" name="orden_material" value="1">1
    <input type="checkbox" name="orden_material" value="2">2
    <input type="checkbox" name="orden_material" value="3">3
    <input type="checkbox" name="orden_material" value="4">4
    <input type="checkbox" name="orden_material" value="5">5
    <input type="checkbox" name="orden_material" value="6">6
    <input type="checkbox" name="orden_material" value="7">7
    <input type="checkbox" name="orden_material" value="8">8
    <input type="checkbox" name="orden_material" value="9">9
    <input type="checkbox" name="orden_material" value="10">10
  </li>
</ul>

## Dinàmiques d'Ensenyament-Aprenentatge

### Estratègies metodològiques observades
<ul>
  <li>
    Diverses activitats realitzades:
    <input type="checkbox" name="variedad_actividades" value="1">1
    <input type="checkbox" name="variedad_actividades" value="2">2
    <input type="checkbox" name="variedad_actividades" value="3">3
    <input type="checkbox" name="variedad_actividades" value="4">4
    <input type="checkbox" name="variedad_actividades" value="5">5
    <input type="checkbox" name="variedad_actividades" value="6">6
    <input type="checkbox" name="variedad_actividades" value="7">7
    <input type="checkbox" name="variedad_actividades" value="8">8
    <input type="checkbox" name="variedad_actividades" value="9">9
    <input type="checkbox" name="variedad_actividades" value="10">10
  </li>
  <li>
    Adaptació de la metodologia al grup:
    <input type="checkbox" name="adecuacion_metodologia" value="1">1
    <input type="checkbox" name="adecuacion_metodologia" value="2">2
    <input type="checkbox" name="adecuacion_metodologia" value="3">3
    <input type="checkbox" name="adecuacion_metodologia" value="4">4
    <input type="checkbox" name="adecuacion_metodologia" value="5">5
    <input type="checkbox" name="adecuacion_metodologia" value="6">6
    <input type="checkbox" name="adecuacion_metodologia" value="7">7
    <input type="checkbox" name="adecuacion_metodologia" value="8">8
    <input type="checkbox" name="adecuacion_metodologia" value="9">9
    <input type="checkbox" name="adecuacion_metodologia" value="10">10
  </li>
  <li>
    Equilibri entre explicació, pràctica i reflexió:
    <input type="checkbox" name="equilibrio" value="1">1
    <input type="checkbox" name="equilibrio" value="2">2
    <input type="checkbox" name="equilibrio" value="3">3
    <input type="checkbox" name="equilibrio" value="4">4
    <input type="checkbox" name="equilibrio" value="5">5
    <input type="checkbox" name="equilibrio" value="6">6
    <input type="checkbox" name="equilibrio" value="7">7
    <input type="checkbox" name="equilibrio" value="8">8
    <input type="checkbox" name="equilibrio" value="9">9
    <input type="checkbox" name="equilibrio" value="10">10
  </li>
  <li>
    Ús de dinàmiques cooperatives o individuals:
    <input type="checkbox" name="dinamicas" value="1">1
    <input type="checkbox" name="dinamicas" value="2">2
    <input type="checkbox" name="dinamicas" value="3">3
    <input type="checkbox" name="dinamicas" value="4">4
    <input type="checkbox" name="dinamicas" value="5">5
    <input type="checkbox" name="dinamicas" value="6">6
    <input type="checkbox" name="dinamicas" value="7">7
    <input type="checkbox" name="dinamicas" value="8">8
    <input type="checkbox" name="dinamicas" value="9">9
    <input type="checkbox" name="dinamicas" value="10">10
  </li>
</ul>

### Comprensió del contingut
<ul>
  <li>
    Evidència de comprensió durant la sessió:
    <input type="checkbox" name="evidencias_comprension" value="1">1
    <input type="checkbox" name="evidencias_comprension" value="2">2
    <input type="checkbox" name="evidencias_comprension" value="3">3
    <input type="checkbox" name="evidencias_comprension" value="4">4
    <input type="checkbox" name="evidencias_comprension" value="5">5
    <input type="checkbox" name="evidencias_comprension" value="6">6
    <input type="checkbox" name="evidencias_comprension" value="7">7
    <input type="checkbox" name="evidencias_comprension" value="8">8
    <input type="checkbox" name="evidencias_comprension" value="9">9
    <input type="checkbox" name="evidencias_comprension" value="10">10
  </li>
  <li>
    Necessitat de repeticions o aclariments:
    <input type="checkbox" name="repeticiones" value="1">1
    <input type="checkbox" name="repeticiones" value="2">2
    <input type="checkbox" name="repeticiones" value="3">3
    <input type="checkbox" name="repeticiones" value="4">4
    <input type="checkbox" name="repeticiones" value="5">5
    <input type="checkbox" name="repeticiones" value="6">6
    <input type="checkbox" name="repeticiones" value="7">7
    <input type="checkbox" name="repeticiones" value="8">8
    <input type="checkbox" name="repeticiones" value="9">9
    <input type="checkbox" name="repeticiones" value="10">10
  </li>
  <li>
    Dificultats generalitzades observades:
    <input type="checkbox" name="dificultades_grupo" value="1">1
    <input type="checkbox" name="dificultades_grupo" value="2">2
    <input type="checkbox" name="dificultades_grupo" value="3">3
    <input type="checkbox" name="dificultades_grupo" value="4">4
    <input type="checkbox" name="dificultades_grupo" value="5">5
    <input type="checkbox" name="dificultades_grupo" value="6">6
    <input type="checkbox" name="dificultades_grupo" value="7">7
    <input type="checkbox" name="dificultades_grupo" value="8">8
    <input type="checkbox" name="dificultades_grupo" value="9">9
    <input type="checkbox" name="dificultades_grupo" value="10">10
  </li>
  <li>
    Heterogeneïtat en el nivell de comprensió:
    <input type="checkbox" name="heterogeneidad" value="1">1
    <input type="checkbox" name="heterogeneidad" value="2">2
    <input type="checkbox" name="heterogeneidad" value="3">3
    <input type="checkbox" name="heterogeneidad" value="4">4
    <input type="checkbox" name="heterogeneidad" value="5">5
    <input type="checkbox" name="heterogeneidad" value="6">6
    <input type="checkbox" name="heterogeneidad" value="7">7
    <input type="checkbox" name="heterogeneidad" value="8">8
    <input type="checkbox" name="heterogeneidad" value="9">9
    <input type="checkbox" name="heterogeneidad" value="10">10
  </li>
</ul>

### Atenció a la diversitat
<ul>
  <li>
    Adaptació a diferents ritmes d'aprenentatge:
    <input type="checkbox" name="adaptacion_ritmos" value="1">1
    <input type="checkbox" name="adaptacion_ritmos" value="2">2
    <input type="checkbox" name="adaptacion_ritmos" value="3">3
    <input type="checkbox" name="adaptacion_ritmos" value="4">4
    <input type="checkbox" name="adaptacion_ritmos" value="5">5
    <input type="checkbox" name="adaptacion_ritmos" value="6">6
    <input type="checkbox" name="adaptacion_ritmos" value="7">7
    <input type="checkbox" name="adaptacion_ritmos" value="8">8
    <input type="checkbox" name="adaptacion_ritmos" value="9">9
    <input type="checkbox" name="adaptacion_ritmos" value="10">10
  </li>
  <li>
    Resposta a necessitats específiques dels alumnes:
    <input type="checkbox" name="respuesta_nese" value="1">1
    <input type="checkbox" name="respuesta_nese" value="2">2
    <input type="checkbox" name="respuesta_nese" value="3">3
    <input type="checkbox" name="respuesta_nese" value="4">4
    <input type="checkbox" name="respuesta_nese" value="5">5
    <input type="checkbox" name="respuesta_nese" value="6">6
    <input type="checkbox" name="respuesta_nese" value="7">7
    <input type="checkbox" name="respuesta_nese" value="8">8
    <input type="checkbox" name="respuesta_nese" value="9">9
    <input type="checkbox" name="respuesta_nese" value="10">10
  </li>
  <li>
    Estratègies d'inclusió observades:
    <input type="checkbox" name="inclusion_apoyos" value="1">1
    <input type="checkbox" name="inclusion_apoyos" value="2">2
    <input type="checkbox" name="inclusion_apoyos" value="3">3
    <input type="checkbox" name="inclusion_apoyos" value="4">4
    <input type="checkbox" name="inclusion_apoyos" value="5">5
    <input type="checkbox" name="inclusion_apoyos" value="6">6
    <input type="checkbox" name="inclusion_apoyos" value="7">7
    <input type="checkbox" name="inclusion_apoyos" value="8">8
    <input type="checkbox" name="inclusion_apoyos" value="9">9
    <input type="checkbox" name="inclusion_apoyos" value="10">10
  </li>
  <li>
    Diferenciació de tasques o suports:
    <input type="checkbox" name="diferenciacion" value="1">1
    <input type="checkbox" name="diferenciacion" value="2">2
    <input type="checkbox" name="diferenciacion" value="3">3
    <input type="checkbox" name="diferenciacion" value="4">4
    <input type="checkbox" name="diferenciacion" value="5">5
    <input type="checkbox" name="diferenciacion" value="6">6
    <input type="checkbox" name="diferenciacion" value="7">7
    <input type="checkbox" name="diferenciacion" value="8">8
    <input type="checkbox" name="diferenciacion" value="9">9
    <input type="checkbox" name="diferenciacion" value="10">10
  </li>
</ul>

## Avaluació global de l'aula
### Percentatge estimat d'alumnes

<ul style="list-style-type: none;">
  <li>
    <strong>Muy implicados:</strong>
    <input type="number" name="muy_implicados" min="0" max="100" size="4" required> %
  </li>
  <br>
  <li>
    <strong>Moderadamente implicados:</strong>
    <input type="number" name="moderadamente_implicados" min="0" max="100" size="4" required> %
  </li>
  <br>
  <li>
    <strong>Poco implicados:</strong>
    <input type="number" name="poco_implicados" min="0" max="100" size="4" required> %
  </li>
  <br>
  <li>
    <strong>Desconectados:</strong>
    <input type="number" name="desconectados" min="0" max="100" size="4" required> %
  </li>
</ul>  

### Puntuació global

<strong>Puntuación global de la sesión:</strong>
<input type="number" name="total" min="0" max="100" size="4" required> %
 

---

## Punts forts del grup

Espai per a notes, comentaris i observacions específiques sobre el grup:

<textarea name="observaciones" rows="8" cols="100" placeholder="Escribe aquí las fortalezas observadas del grupo..." style="width: 100%; padding: 10px; font-family: inherit; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;"></textarea>

---

## Àrees de millora

Espai per a notes, comentaris i observacions específiques sobre el grup:

<textarea name="recomendaciones" rows="8" cols="100" placeholder="Escribe aquí las áreas de mejora observadas del grupo..." style="width: 100%; padding: 10px; font-family: inherit; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;"></textarea>

---

## Situacions o incidències rellevants

Espai per a notes, comentaris i observacions específiques sobre el grup:

<textarea name="recomendaciones" rows="8" cols="100" placeholder="Escribe aquí las situaciones o incidencias relevantes del grupo..." style="width: 100%; padding: 10px; font-family: inherit; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;"></textarea>

---

## Propostes d'intervenció o seguiment

Espai per a notes, comentaris i observacions específiques sobre el grup:

<textarea name="recomendaciones" rows="8" cols="100" placeholder="Escribe aquí las propuestas de intervención o seguimiento..." style="width: 100%; padding: 10px; font-family: inherit; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;"></textarea>

---

## Observacions addicionals

Espai per a apunts, comentaris i observacions específiques sobre l'alumne:

<textarea name="observaciones" rows="8" cols="100" placeholder="Escribe aquí tus observaciones adicionales..." style="width: 100%; padding: 10px; font-family: inherit; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;"></textarea>

---

```{=html}
<div id="pdf-btn-container" style="text-align: center; margin: 2em 0;">
  <button onclick="imprimirPDF()" style="
    background-color: #0f5c6e;
    color: white;
    border: none;
    padding: 14px 32px;
    font-size: 16px;
    font-weight: bold;
    border-radius: 6px;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    gap: 10px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.2);
  ">
    ⬇ Descarregar com a PDF
  </button>
  <p style="font-size: 13px; color: #666; margin-top: 8px;">
    Al diàleg d'impressió, selecciona <strong>«Desa com a PDF»</strong> com a destí.
  </p>
</div>

<script>
function imprimirPDF() {
  const curso      = document.querySelector('input[name="curso"]')?.value?.trim();
  const asignatura = document.querySelector('input[name="asignatura"]')?.value?.trim();
  const fecha      = document.querySelector('input[name="fecha_observacion"]')?.value;

  if (!curso && !asignatura) {
    const ok = confirm("Els camps «Curs» i «Assignatura» estan buits.\nVols continuar de totes maneres?");
    if (!ok) return;
  }

  const tituloOriginal = document.title;
  const partes = ["Observacio_Aula", curso, asignatura, fecha].filter(Boolean);
  document.title = partes.join("_").replace(/\s+/g, "_");

  window.print();

  setTimeout(() => { document.title = tituloOriginal; }, 1500);
}
</script>

<style>
@media print {
  .navbar, .nav-footer, #quarto-sidebar, #TOC, .quarto-title-banner,
  .quarto-title-meta, #pdf-btn-container, .page-navigation,
  #quarto-margin-sidebar, header.quarto-title-block, .quarto-secondary-nav {
    display: none !important;
  }
  body { font-size: 11pt; color: #000; }
  #quarto-content { margin: 0 !important; padding: 0 !important; max-width: 100% !important; }
  input[type="text"],
  input[type="date"],
  input[type="number"] {
    border: none !important;
    border-bottom: 1px solid #555 !important;
    background: transparent !important;
    box-shadow: none !important;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  input[type="checkbox"] {
    width: 13px;
    height: 13px;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
    appearance: auto;
    -webkit-appearance: auto;
  }
  textarea {
    border: 1px solid #999 !important;
    min-height: 80px;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  h2 { page-break-before: always; }
  h2:first-of-type { page-break-before: avoid; }
}
</style>
```